import { GameCommandType } from '@game/application/game-commands';
import { TUTORIAL_CHECKPOINT_IDS, type TutorialCheckpointId } from '@game/online/tutorial-types';
import { GamePhase, SlotPosition, SubPhase, ZoneType } from '@game/shared/types/enums';
import { BATTLE_UI_ANCHORS } from '@/lib/battleUiAnchors';
import type { TutorialCommandRule, TutorialScenarioDefinition } from '@/lib/tutorialScenario';

export const BASIC_LIVE_TUTORIAL_ID = 'basic-live-loop';
export const BASIC_LIVE_TUTORIAL_VERSION = '1.1.5';

export interface BasicLiveTutorialCheckpointOption {
  readonly id: TutorialCheckpointId;
  readonly entryStepId: string;
  readonly title: string;
  readonly summary: string;
  readonly durationLabel: string;
  readonly recommended?: boolean;
}

export const BASIC_LIVE_TUTORIAL_CHECKPOINTS: readonly BasicLiveTutorialCheckpointOption[] = [
  {
    id: TUTORIAL_CHECKPOINT_IDS.FOUNDATIONS,
    entryStepId: 'welcome',
    title: '基础规则与首轮 LIVE',
    summary: '从开局准备练到三回合终局',
    durationLabel: '约 10 分钟',
    recommended: true,
  },
  {
    id: TUTORIAL_CHECKPOINT_IDS.LIVE_EFFECTS,
    entryStepId: 'advanced-welcome',
    title: '换手与触发能力',
    summary: '从换手减费与登场能力练到终局',
    durationLabel: '约 8 分钟',
  },
  {
    id: TUTORIAL_CHECKPOINT_IDS.RECOVERY_LOOP,
    entryStepId: 'third-turn-arrival',
    title: '起动能力与资源循环',
    summary: '从起动回收与剩余能量练到终局',
    durationLabel: '约 6 分钟',
  },
  {
    id: TUTORIAL_CHECKPOINT_IDS.FINISHING_LIVE,
    entryStepId: 'count-final-stage-hearts',
    title: '场攻估算与 LIVE 配置',
    summary: '估算场攻、评估风险并配置制胜 LIVE',
    durationLabel: '约 4 分钟',
  },
];

export const BASIC_LIVE_TUTORIAL_OBJECT_ROLES = {
  MULLIGAN_CARD: 'opening-mulligan-card',
  MEMBER_CARD: 'tutorial-member-card',
  LIVE_CARD: 'tutorial-live-card',
  RELAY_MEMBER: 'tutorial-relay-member',
  EFFECT_LIVE_CARD: 'tutorial-effect-live-card',
  RECOVERY_MEMBER: 'tutorial-recovery-member',
  FINAL_LIVE_ONE: 'tutorial-final-live-one',
  FINAL_LIVE_TWO: 'tutorial-final-live-two',
  FINAL_LIVE_RISKY: 'tutorial-final-live-risky',
  OPPONENT_SECOND_MEMBER: 'opponent-second-member',
  OPPONENT_SECOND_LIVE: 'opponent-second-live',
  OPPONENT_RELAY_MEMBER: 'opponent-relay-member',
  OPPONENT_FINAL_RELAY_MEMBER: 'opponent-final-relay-member',
  OPPONENT_THIRD_MEMBER: 'opponent-third-member',
  OPPONENT_FINAL_LIVE: 'opponent-final-set-card',
} as const;

const MULLIGAN_RULE: TutorialCommandRule = {
  commandType: GameCommandType.MULLIGAN,
  exactObjectRoles: [BASIC_LIVE_TUTORIAL_OBJECT_ROLES.MULLIGAN_CARD],
};

const PLAY_MEMBER_RULE: TutorialCommandRule = {
  commandType: GameCommandType.PLAY_MEMBER_TO_SLOT,
  objectRole: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.MEMBER_CARD,
  targetSlot: SlotPosition.CENTER,
};

const END_MAIN_PHASE_RULE: TutorialCommandRule = {
  commandType: GameCommandType.END_PHASE,
};

const SET_LIVE_RULE: TutorialCommandRule = {
  commandType: GameCommandType.SET_LIVE_CARD,
  objectRole: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.LIVE_CARD,
  faceDown: true,
};

const CONFIRM_LIVE_SET_RULE: TutorialCommandRule = {
  commandType: GameCommandType.CONFIRM_STEP,
  subPhase: SubPhase.LIVE_SET_FIRST_PLAYER,
};

const ACCEPT_AUTOMATIC_JUDGMENT_RULE: TutorialCommandRule = {
  commandType: GameCommandType.SUBMIT_JUDGMENT,
  automaticJudgmentOnly: true,
};

const CONFIRM_JUDGMENT_SUBPHASE_RULE: TutorialCommandRule = {
  commandType: GameCommandType.CONFIRM_STEP,
  subPhase: SubPhase.PERFORMANCE_JUDGMENT,
};

const CONFIRM_COMPUTED_SCORE_RULE: TutorialCommandRule = {
  commandType: GameCommandType.SUBMIT_SCORE,
  computedScoreOnly: true,
};

const CONFIRM_RESULT_ANIMATION_RULE: TutorialCommandRule = {
  commandType: GameCommandType.CONFIRM_STEP,
  subPhase: SubPhase.RESULT_ANIMATION,
};

const SELECT_SUCCESS_LIVE_RULE: TutorialCommandRule = {
  commandType: GameCommandType.SELECT_SUCCESS_LIVE,
  objectRole: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.LIVE_CARD,
};

const CONFIRM_SETTLEMENT_RULE: TutorialCommandRule = {
  commandType: GameCommandType.CONFIRM_STEP,
  subPhase: SubPhase.RESULT_SETTLEMENT,
};

const RELAY_MEMBER_RULE: TutorialCommandRule = {
  commandType: GameCommandType.PLAY_MEMBER_TO_SLOT,
  objectRole: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.RELAY_MEMBER,
  targetSlot: SlotPosition.CENTER,
};

const SET_EFFECT_LIVE_RULE: TutorialCommandRule = {
  commandType: GameCommandType.SET_LIVE_CARD,
  objectRole: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.EFFECT_LIVE_CARD,
  faceDown: true,
};

const RESOLVE_EFFECT_RULE: TutorialCommandRule = {
  commandType: GameCommandType.CONFIRM_EFFECT_STEP,
};

const SELECT_EFFECT_SUCCESS_LIVE_RULE: TutorialCommandRule = {
  commandType: GameCommandType.SELECT_SUCCESS_LIVE,
  objectRole: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.EFFECT_LIVE_CARD,
};

const PLAY_RECOVERY_MEMBER_RULE: TutorialCommandRule = {
  commandType: GameCommandType.PLAY_MEMBER_TO_SLOT,
  objectRole: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.RECOVERY_MEMBER,
  targetSlot: SlotPosition.LEFT,
};

const ACTIVATE_RECOVERY_MEMBER_RULE: TutorialCommandRule = {
  commandType: GameCommandType.ACTIVATE_ABILITY,
  objectRole: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.RECOVERY_MEMBER,
};

const REPLAY_RECOVERED_MEMBER_RULE: TutorialCommandRule = {
  commandType: GameCommandType.PLAY_MEMBER_TO_SLOT,
  objectRole: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.MEMBER_CARD,
  targetSlot: SlotPosition.LEFT,
};

const SET_FINAL_LIVE_ONE_RULE: TutorialCommandRule = {
  commandType: GameCommandType.SET_LIVE_CARD,
  objectRole: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.FINAL_LIVE_ONE,
  faceDown: true,
};

const SET_FINAL_LIVE_TWO_RULE: TutorialCommandRule = {
  commandType: GameCommandType.SET_LIVE_CARD,
  objectRole: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.FINAL_LIVE_TWO,
  faceDown: true,
};

const SELECT_FINAL_SUCCESS_LIVE_RULE: TutorialCommandRule = {
  commandType: GameCommandType.SELECT_SUCCESS_LIVE,
  objectRole: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.FINAL_LIVE_TWO,
};

/**
 * Public tutorial content only. The authoritative scene, card codes, deck order,
 * deterministic random decisions, and opponent script must stay on the server.
 */
export const BASIC_LIVE_TUTORIAL: TutorialScenarioDefinition = {
  id: BASIC_LIVE_TUTORIAL_ID,
  version: BASIC_LIVE_TUTORIAL_VERSION,
  contentVersion: 15,
  objectRoles: Object.values(BASIC_LIVE_TUTORIAL_OBJECT_ROLES),
  steps: [
    {
      id: 'welcome',
      contentVersion: 1,
      kind: 'INFO',
      chapter: '认识游戏',
      title: '跟着小铃，完成一次 LIVE',
      body: '我们会一起走过换牌、成员登场、LIVE 设置、判定和结算。别急，每个要操作的地方都会停下来等你。',
      mascot: 'WELCOME',
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'member-card',
      contentVersion: 1,
      kind: 'INFO',
      chapter: '认识游戏',
      title: '成员卡负责登上舞台',
      body: '成员会提供 Heart，并可能拥有能力。登场时需要由能量支付费用。',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.MEMBER_CARD,
        placement: 'TOP',
      },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'live-card',
      contentVersion: 1,
      kind: 'INFO',
      chapter: '认识游戏',
      title: 'LIVE 卡决定表演目标',
      body: 'LIVE 卡有必要 Heart 和分数。表演时满足必要 Heart，才能让这张 LIVE 成功。',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.LIVE_CARD,
        placement: 'TOP',
      },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'win-goal',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '认识游戏',
      title: '把成功的 LIVE 留下来',
      body: '每轮取得 LIVE 胜利后，从自己本轮成功的 LIVE 中选 1 张放入成功 LIVE 区；率先累积 3 张成功 LIVE 即获得整局胜利。',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.SELF_SUCCESS_LIVE_ZONE,
        placement: 'RIGHT',
      },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'self-hand',
      contentVersion: 1,
      kind: 'INFO',
      chapter: '认识区域',
      title: '这是你的手牌',
      body: '只有你能看到自己的手牌正面。对手只能知道手牌数量。',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_HAND, placement: 'TOP' },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'main-deck',
      contentVersion: 1,
      kind: 'INFO',
      chapter: '认识区域',
      title: '主卡组提供成员与 LIVE',
      body: '抽牌通常从主卡组顶进入手牌；牌序仍是隐藏信息。',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_MAIN_DECK },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'energy-deck',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '认识区域',
      title: '能量来自独立卡组',
      body: '开局准备会先从能量卡组放置 3 张初始能量；之后的能量阶段会继续补充能量，供成员登场支付费用。',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_ENERGY_DECK },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'energy-zone',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '认识区域',
      title: '能量区记录可用资源',
      body: '支付费用时，规则会把活跃能量变为待机状态。教程只读取规则处理后的真实结果。',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_ENERGY_ZONE },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'stage',
      contentVersion: 1,
      kind: 'INFO',
      chapter: '认识区域',
      title: '舞台分为左、中、右三个位置',
      body: '成员登场到具体位置。首版会让指定成员登场到中央。',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_STAGE_CENTER },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'live-zone',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '认识区域',
      title: 'LIVE 区等待本轮表演',
      body: 'LIVE 设置时先盖放卡牌；双方完成设置后，先攻的 LIVE 先公开并表演，再轮到后攻。',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_LIVE_ZONE },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'waiting-room',
      contentVersion: 1,
      kind: 'INFO',
      chapter: '认识区域',
      title: '使用后的卡会进入休息室',
      body: '休息室是公开区域。失败或未选为成功 LIVE 的卡也可能在结算时进入这里。',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_WAITING_ROOM },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'mulligan-explain',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '开局准备',
      title: '先调整起始手牌',
      body: '正式对局开局时，每位玩家抽 6 张起始手牌并放置 3 张初始能量；对局前猜拳的胜者选择先攻或后攻。本教程为保证流程稳定，固定由你先攻。下一步换掉提示的 1 张牌；规则会换回同样数量的牌并真实洗牌。',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.MULLIGAN_PANEL },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'mulligan-card',
      contentVersion: 2,
      kind: 'ACTION',
      chapter: '开局准备',
      title: '换掉这 1 张牌',
      body: '先点击高亮卡牌将它选中，再点击面板下方的“换 1 张”确认。只有确认后才会提交正式换牌命令，其他牌在此步骤不可选择。',
      statusText: '等待你选中高亮牌并点击“换 1 张”确认',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.MULLIGAN_CARD,
        placement: 'TOP',
      },
      allowedCommands: [MULLIGAN_RULE],
      completion: { kind: 'ACCEPTED_COMMAND', command: MULLIGAN_RULE },
    },
    {
      id: 'opening-transition',
      contentVersion: 1,
      kind: 'OBSERVE',
      chapter: '基础回合',
      title: '等待对手完成换牌',
      body: '你的换牌会先完整播放；随后对手确认起手，规则依次完成活跃、能量与抽卡流程，再把操作权交给你。',
      statusText: '正在通过正式规则进入你的主要阶段',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.PHASE_CONTROLS },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'MATCH',
          phase: GamePhase.MAIN_PHASE,
          activeSeat: 'VIEWER',
        },
      },
    },
    {
      id: 'turn-phases',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '基础回合',
      title: '通常阶段依次经过四个阶段',
      body: '活跃阶段恢复卡牌，能量阶段补充资源，抽卡阶段加入手牌，主要阶段由你登场成员和使用能力。',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.PHASE_CONTROLS },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'play-member',
      contentVersion: 2,
      kind: 'ACTION',
      chapter: '基础回合',
      title: '让成员登场到中央',
      body: '把手牌中的费用 4「桂城 泉」拖到蓝色高亮的中央舞台；也可以先选中费用 4「桂城 泉」，再点击蓝色高亮的中央区域。两种方式都会提交同一个正式登场命令，并由规则校验位置、自动支付费用。',
      statusText: '等待指定成员合法登场到中央',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.SELF_STAGE_CENTER,
        placement: 'TOP',
      },
      secondaryTargets: [
        {
          kind: 'OBJECT_ROLE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.MEMBER_CARD,
          padding: 8,
        },
      ],
      allowedCommands: [PLAY_MEMBER_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: PLAY_MEMBER_RULE,
        postCondition: {
          kind: 'OBJECT_IN_ZONE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.MEMBER_CARD,
          seat: 'VIEWER',
          zone: ZoneType.MEMBER_SLOT,
          slot: SlotPosition.CENTER,
        },
      },
    },
    {
      id: 'cost-paid',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '基础回合',
      title: '登场费用已经由规则支付',
      body: '变为待机状态的能量记录了本次支付。教程只解释规则结果，不另做一套费用状态。',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_ENERGY_ZONE },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'end-main-phase',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '对手回合',
      title: '结束自己的主要阶段',
      body: '使用阶段控制的正式按钮交出操作权。对手随后会通过正常命令完成预定动作。',
      statusText: '等待主要阶段结束命令被接受',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.PHASE_PRIMARY_ACTION },
      allowedCommands: [END_MAIN_PHASE_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: END_MAIN_PHASE_RULE,
        postCondition: { kind: 'MATCH', excludedPhases: [GamePhase.MAIN_PHASE] },
      },
    },
    {
      id: 'opponent-turn',
      contentVersion: 2,
      kind: 'OBSERVE',
      chapter: '对手回合',
      title: '观察对手完成基础回合',
      body: '对手的登场、支付与阶段结束都由脚本通过正式命令完成；你仍只能看到规则允许公开的信息。',
      statusText: '对手正在行动，等待进入 LIVE 设置',
      completionDwellMs: 2_600,
      completionDwellStatusText: '对手已完成行动，请看清本步后进入 LIVE 设置',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.OPPONENT_AREA },
      completion: {
        kind: 'VIEW_STATE',
        condition: { kind: 'MATCH', phase: GamePhase.LIVE_SET_PHASE },
      },
    },
    {
      id: 'live-set-explain',
      contentVersion: 1,
      kind: 'INFO',
      chapter: 'LIVE 设置',
      title: '盖放本轮要表演的 LIVE',
      body: '设置和完成设置是两个正式动作。这样可以在结束前检查自己的选择。',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_LIVE_ZONE },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'set-live-card',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: 'LIVE 设置',
      title: '设置这张 LIVE',
      body: '把高亮 LIVE 放入自己的 LIVE 区。它会先保持盖放，不向对手泄露正面信息。',
      statusText: '等待指定 LIVE 合法进入 LIVE 区',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.LIVE_CARD,
        placement: 'TOP',
      },
      allowedCommands: [SET_LIVE_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: SET_LIVE_RULE,
        postCondition: {
          kind: 'OBJECT_IN_ZONE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.LIVE_CARD,
          seat: 'VIEWER',
          zone: ZoneType.LIVE_ZONE,
        },
      },
    },
    {
      id: 'confirm-live-set',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: 'LIVE 设置',
      title: '确认完成 LIVE 设置',
      body: '使用阶段控制按钮确认。确认后，设置动作才正式结束。',
      statusText: '等待 LIVE 设置确认命令被接受',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.PHASE_PRIMARY_ACTION },
      allowedCommands: [CONFIRM_LIVE_SET_RULE],
      completion: { kind: 'ACCEPTED_COMMAND', command: CONFIRM_LIVE_SET_RULE },
    },
    {
      id: 'watch-cheer',
      contentVersion: 2,
      kind: 'OBSERVE',
      chapter: 'LIVE 表演',
      title: '观察公开、应援与 Heart 汇总',
      body: '共享牌桌会按真实结果公开 LIVE、进行应援并汇总 Heart。动画可以缩短，但不能替代权威结果。',
      statusText: '正在等待你的自动判定确认窗口',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.JUDGMENT_SUMMARY },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'ALL',
          conditions: [
            { kind: 'MATCH', subPhase: SubPhase.PERFORMANCE_JUDGMENT },
            { kind: 'COMMAND_AVAILABLE', commandType: GameCommandType.SUBMIT_JUDGMENT },
          ],
        },
      },
    },
    {
      id: 'judgment-card-source',
      contentVersion: 3,
      kind: 'INFO',
      chapter: 'LIVE 表演',
      title: '先看判定区里的牌从哪里来',
      body: '表演进行应援时，会从自己的主卡组顶按顺序公开卡牌到判定区。通常公开张数由舞台上活跃成员的 BLADE 合计决定；公开卡上的 BLADE HEART 会成为“判心”，抽卡图标则会立即处理抽卡。',
      mascot: 'READ_CARD',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.JUDGMENT_CHEER_CARDS,
        placement: 'RIGHT',
      },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'read-judgment-summary',
      contentVersion: 2,
      kind: 'INFO',
      chapter: 'LIVE 表演',
      title: '再把 Heart 与 LIVE 需求对起来',
      body: '“判定 Heart”会把舞台成员提供的 Heart 与这次应援得到的判心分开列出并汇总；“LIVE 需求”逐张显示必要 Heart 与缺口；“接受后预计”则显示成功或失败、抽卡与合计分数。All Heart 可以补任意指定颜色。',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.JUDGMENT_SUMMARY,
        placement: 'RIGHT',
      },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'accept-automatic-judgment',
      contentVersion: 2,
      kind: 'ACTION',
      chapter: 'LIVE 表演',
      title: '核对后接受规则计算的自动判定',
      body: '确认 Heart 来源、每张 LIVE 的必要 Heart 和“接受后预计”都符合刚才的说明，再接受自动结果。教程不允许在这里手动改判。',
      statusText: '等待你使用共享判定面板确认',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.AUTOMATIC_JUDGMENT_CONFIRM,
        placement: 'TOP',
      },
      // The shared button submits the automatic result and confirms this subphase as one UI action.
      allowedCommands: [ACCEPT_AUTOMATIC_JUDGMENT_RULE, CONFIRM_JUDGMENT_SUBPHASE_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: ACCEPT_AUTOMATIC_JUDGMENT_RULE,
        additionalCommands: [CONFIRM_JUDGMENT_SUBPHASE_RULE],
      },
    },
    {
      id: 'opponent-member-skips-live',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '判定与计分',
      title: '没有 LIVE，就会跳过表演',
      body: '对手刚才盖放的是成员卡。轮到对手 LIVE 时，规则先把 LIVE 区的盖牌翻开；表侧成员卡会立即从 LIVE 区放置入休息室。处理后对手的 LIVE 区没有 LIVE 卡，因此直接跳过 LIVE 开始、应援与判定。',
      pauseScript: true,
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.PHASE_CONTROLS,
        placement: 'TOP',
      },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'wait-score',
      contentVersion: 2,
      kind: 'OBSERVE',
      chapter: '判定与计分',
      title: '等待进入分数确认',
      body: '你已完成表演，对手则因没有 LIVE 跳过表演。规则现在会结束双方必要的成功效果窗口，并计算本轮分数。',
      statusText: '正在等待分数确认窗口',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.JUDGMENT_PANEL },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'ALL',
          conditions: [
            { kind: 'MATCH', subPhase: SubPhase.RESULT_SCORE_CONFIRM },
            { kind: 'COMMAND_AVAILABLE', commandType: GameCommandType.SUBMIT_SCORE },
          ],
        },
      },
    },
    {
      id: 'confirm-score',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '判定与计分',
      title: '确认规则计算的分数',
      body: '检查分数构成并确认当前值。教程规则模式不开放手动调分。',
      statusText: '等待你确认当前计算分数',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SCORE_CONFIRM_ACTION },
      allowedCommands: [CONFIRM_COMPUTED_SCORE_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: CONFIRM_COMPUTED_SCORE_RULE,
        postCondition: { kind: 'LIVE_SCORE_CONFIRMED', seat: 'VIEWER' },
      },
    },
    {
      id: 'confirm-result-animation',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '判定与计分',
      title: '确认本轮结果',
      body: '结果演出只负责反馈胜负；点击继续会提交正式结算步骤，而不是只关闭动画。',
      statusText: '等待你继续正式结算',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.RESULT_ANIMATION_CONFIRM },
      allowedCommands: [CONFIRM_RESULT_ANIMATION_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: CONFIRM_RESULT_ANIMATION_RULE,
        postCondition: { kind: 'MATCH', subPhase: SubPhase.RESULT_SETTLEMENT },
      },
    },
    {
      id: 'select-success-live',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '判定与计分',
      title: '选择本轮成功的 LIVE',
      body: '选择高亮的获胜 LIVE。只有规则层给出的候选可以进入成功 LIVE 区。',
      statusText: '等待你选择指定的成功 LIVE',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SUCCESS_LIVE_CANDIDATES },
      allowedCommands: [SELECT_SUCCESS_LIVE_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: SELECT_SUCCESS_LIVE_RULE,
        postCondition: {
          kind: 'OBJECT_IN_ZONE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.LIVE_CARD,
          seat: 'VIEWER',
          zone: ZoneType.SUCCESS_ZONE,
        },
      },
    },
    {
      id: 'confirm-settlement',
      contentVersion: 2,
      kind: 'ACTION',
      chapter: '判定与计分',
      title: '确认成功 LIVE 结算',
      body: '双方 LIVE 都成功且分数平分时，成功 LIVE 区少于 2 张的一方取得本轮胜利；双方都少于 2 张时双方都胜利，都已有 2 张时本轮无人胜利。若双方在同次结算后都达到 3 张，整局平局。只有一方实际放入成功 LIVE 时，该方成为下回合先攻；双方都放入或都未放入时，先攻不变。现在确认结算进入下一回合。',
      statusText: '等待最终结算确认命令被接受',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.PHASE_PRIMARY_ACTION },
      allowedCommands: [CONFIRM_SETTLEMENT_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: CONFIRM_SETTLEMENT_RULE,
        postCondition: {
          kind: 'MATCH',
          excludedSubPhases: [SubPhase.RESULT_SETTLEMENT],
        },
      },
    },
    {
      id: 'advanced-welcome',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '第二回合 · 主要阶段',
      title: '第二回合，来看看新手牌',
      body: '活跃、能量与抽卡阶段已经完成。现在先看看刚刚加入手牌的成员。',
      mascot: 'WELCOME',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.PHASE_CONTROLS },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'read-relay-cost',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '第二回合 · 阅读卡面',
      title: '先看费用与换手减免',
      body: '费用 9「钟岚珠」要换手登场到中央。中央的费用 4「桂城 泉」会提供 4 点换手减免，因此规则实际自动支付 5 点能量。',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.RELAY_MEMBER,
        placement: 'TOP',
      },
      secondaryTargets: [
        { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_STAGE_CENTER },
        { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_ENERGY_ZONE },
      ],
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'read-hearts-and-blade',
      contentVersion: 3,
      kind: 'INFO',
      chapter: '第二回合 · 阅读卡面',
      title: 'Heart 与 BLADE 各自负责什么',
      body: '她会为 LIVE 提供 [桃ハート][黄ハート][緑ハート]。她的 [BLADE] 数值是 3，且只有活跃状态的舞台成员会把自己的 [BLADE] 计入基础应援张数。',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.RELAY_MEMBER,
        placement: 'TOP',
      },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'read-on-enter-effect',
      contentVersion: 3,
      kind: 'INFO',
      chapter: '第二回合 · 阅读卡面',
      title: '【登场】表示能力的触发时点',
      body: '能力写着“【登场】抽 2 张卡，将 2 张手牌放置入休息室”。换手登场仍属于登场，因此这项登场能力会进入处理流程；需要选择哪 2 张手牌时，决定仍由你完成。',
      mascot: 'READ_CARD',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.RELAY_MEMBER,
        placement: 'TOP',
      },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'relay-to-center',
      contentVersion: 2,
      kind: 'ACTION',
      chapter: '第二回合 · 成员换手',
      title: '把费用 9 成员换手登场到中央',
      body: '先选中高亮手牌，再点击高亮的中央舞台；也可以直接拖到中央。规则会把原成员送入休息室，并按换手减免自动支付 5 点能量。',
      statusText: '等待费用 9「钟岚珠」换手登场到中央',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.SELF_STAGE_CENTER,
        placement: 'TOP',
      },
      secondaryTargets: [
        {
          kind: 'OBJECT_ROLE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.RELAY_MEMBER,
          padding: 8,
        },
      ],
      allowedCommands: [RELAY_MEMBER_RULE],
      completion: { kind: 'ACCEPTED_COMMAND', command: RELAY_MEMBER_RULE },
    },
    {
      id: 'effect-window',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '第二回合 · 登场能力',
      title: '登场能力触发后仍由你选择',
      body: '登场事件已经让能力进入效果面板，前半段的抽 2 张也已经执行。面板会显示来源卡、效果原文和当前步骤；后半段仍要由你选择 2 张手牌。',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.ACTIVE_EFFECT_PANEL,
        placement: 'TOP',
      },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'resolve-relay-discard',
      contentVersion: 3,
      kind: 'ACTION',
      chapter: '第二回合 · 登场能力',
      title: '保留 LIVE，选择 2 张成员卡',
      body: '手牌中的 LIVE 后面都会用来练习配置，不要把它们放入休息室。请在效果面板中选择 2 张成员卡并确认。',
      statusText: '等待你保留 LIVE，并选择 2 张成员卡',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.ACTIVE_EFFECT_SELECTION,
        placement: 'TOP',
      },
      secondaryTargets: [
        { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.ACTIVE_EFFECT_CONFIRM },
        {
          kind: 'OBJECT_ROLE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.EFFECT_LIVE_CARD,
        },
      ],
      allowedCommands: [RESOLVE_EFFECT_RULE],
      completion: { kind: 'ACCEPTED_COMMAND', command: RESOLVE_EFFECT_RULE },
    },
    {
      id: 'read-effect-live',
      contentVersion: 1,
      kind: 'INFO',
      chapter: '第二回合 · 特殊 LIVE',
      title: 'LIVE 卡本身也可以持有效果',
      body: '分数 1「Very! Very! COCO夏っ」的必要 Heart 包含 [桃ハート][緑ハート][無ハート]。卡文“【LIVE开始时】抽 1 张卡，将 1 张手牌放置入休息室”会在这张 LIVE 翻开并进入 LIVE 开始检查时点后触发。',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.EFFECT_LIVE_CARD,
        placement: 'TOP',
      },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'end-second-main',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第二回合 · 特殊 LIVE',
      title: '结束主要阶段',
      body: '交出操作权后，对手会继续补充舞台，再进入第二轮 LIVE 设置。',
      statusText: '等待第二回合主要阶段结束',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.PHASE_PRIMARY_ACTION },
      allowedCommands: [END_MAIN_PHASE_RULE],
      completion: { kind: 'ACCEPTED_COMMAND', command: END_MAIN_PHASE_RULE },
    },
    {
      id: 'opponent-second-relay',
      contentVersion: 1,
      kind: 'OBSERVE',
      chapter: '第二回合 · 特殊 LIVE',
      title: '对手也用换手强化中央',
      body: '费用 7「东条希」替换中央的费用 4「高坂穗乃果」，换手后只支付 3 点能量。中央因此从 2 Heart、1 个 [BLADE] 提升为 3 Heart、2 个 [BLADE]。',
      statusText: '正在观察对手的换手登场',
      completionDwellMs: 1_200,
      completionDwellStatusText: '对手已经完成中央换手',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.OPPONENT_STAGE_CENTER },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'OBJECT_IN_ZONE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.OPPONENT_RELAY_MEMBER,
          seat: 'OPPONENT',
          zone: ZoneType.MEMBER_SLOT,
          slot: SlotPosition.CENTER,
        },
      },
    },
    {
      id: 'opponent-second-turn',
      contentVersion: 3,
      kind: 'OBSERVE',
      chapter: '第二回合 · 特殊 LIVE',
      title: '再用剩余能量补上左侧',
      body: '换手支付 3 点后，对手用剩余 2 点让费用 2「星空凛」登场到左侧。两名成员合计 4 Heart、3 个 [BLADE]，估算场攻从第一回合的 3 提高到了 7。',
      statusText: '正在观察对手的成员登场',
      completionDwellMs: 1_200,
      completionDwellStatusText: '对手已完成成员登场，即将进入 LIVE 设置',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.OPPONENT_STAGE_LEFT },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'ALL',
          conditions: [
            { kind: 'MATCH', phase: GamePhase.LIVE_SET_PHASE },
            {
              kind: 'OBJECT_IN_ZONE',
              role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.OPPONENT_SECOND_MEMBER,
              seat: 'OPPONENT',
              zone: ZoneType.MEMBER_SLOT,
              slot: SlotPosition.LEFT,
            },
          ],
        },
      },
    },
    {
      id: 'set-effect-live',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第二回合 · 特殊 LIVE',
      title: '设置带【LIVE开始时】能力的 LIVE',
      body: '把高亮 LIVE 放入自己的 LIVE 区。它仍会先以里侧状态盖放，确认设置后才会在表演阶段公开。',
      statusText: '等待特殊 LIVE 进入 LIVE 区',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.EFFECT_LIVE_CARD,
        placement: 'TOP',
      },
      allowedCommands: [SET_EFFECT_LIVE_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: SET_EFFECT_LIVE_RULE,
        postCondition: {
          kind: 'OBJECT_IN_ZONE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.EFFECT_LIVE_CARD,
          seat: 'VIEWER',
          zone: ZoneType.LIVE_ZONE,
        },
      },
    },
    {
      id: 'confirm-effect-live-set',
      contentVersion: 2,
      kind: 'ACTION',
      chapter: '第二回合 · 特殊 LIVE',
      title: '确认完成 LIVE 设置',
      body: '确认后会轮到对手设置 LIVE。双方完成设置后，先公开并表演先攻的 LIVE，再公开后攻的 LIVE。',
      statusText: '等待 LIVE 设置确认',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.PHASE_PRIMARY_ACTION },
      allowedCommands: [CONFIRM_LIVE_SET_RULE],
      completion: { kind: 'ACCEPTED_COMMAND', command: CONFIRM_LIVE_SET_RULE },
    },
    {
      id: 'opponent-second-live-set',
      contentVersion: 2,
      kind: 'OBSERVE',
      chapter: '第二回合 · 对手 LIVE',
      title: '对手也盖下了这轮 LIVE',
      body: '现在双方的 LIVE 区都有里侧牌，一场 LIVE 对决已经准备好了。对手的卡暂时不能提前查看；你的 LIVE 会先公开表演，之后再轮到对手。',
      statusText: '正在等待对手完成 LIVE 设置',
      completionDwellMs: 1_200,
      completionDwellStatusText: '双方已经盖好 LIVE，准备依次表演',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.OPPONENT_LIVE_ZONE },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'ALL',
          conditions: [
            {
              kind: 'MATCH',
              phase: GamePhase.LIVE_SET_PHASE,
              subPhase: SubPhase.LIVE_SET_SECOND_PLAYER,
            },
            {
              kind: 'ZONE_CARD_COUNT',
              seat: 'OPPONENT',
              zone: ZoneType.LIVE_ZONE,
              minimumCount: 1,
            },
          ],
        },
      },
    },
    {
      id: 'wait-live-start-effect',
      contentVersion: 2,
      kind: 'OBSERVE',
      chapter: '第二回合 · LIVE 开始',
      title: 'LIVE 公开后，先处理 LIVE 开始能力',
      body: '应援和判定不会抢先发生。规则先建立 LIVE 开始检查时点，并把这张 LIVE 的强制能力放进共享效果面板。',
      statusText: '正在等待 LIVE 开始能力窗口',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.ACTIVE_EFFECT_PANEL },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'ALL',
          conditions: [
            { kind: 'MATCH', subPhase: SubPhase.PERFORMANCE_LIVE_START_EFFECTS },
            { kind: 'COMMAND_AVAILABLE', commandType: GameCommandType.CONFIRM_EFFECT_STEP },
          ],
        },
      },
    },
    {
      id: 'explain-live-start-effect',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '第二回合 · LIVE 开始',
      title: '触发时点来自 LIVE 卡，而不是舞台成员',
      body: '面板来源是刚公开的 LIVE。能力先自动抽 1 张，再停下来让你决定哪 1 张手牌进入休息室；完成整个能力后，才继续本轮应援和自动判定。',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.ACTIVE_EFFECT_PANEL,
        placement: 'TOP',
      },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'resolve-live-start-discard',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第二回合 · LIVE 开始',
      title: '选择 1 张成员卡完成 LIVE 开始能力',
      body: '从效果面板中点击 1 张成员卡，将它放入休息室；保留手牌中的 LIVE。抽牌与弃牌属于同一项能力的连续步骤。',
      statusText: '等待你选择 1 张成员卡放入休息室',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.ACTIVE_EFFECT_SELECTION,
        placement: 'TOP',
      },
      allowedCommands: [RESOLVE_EFFECT_RULE],
      completion: { kind: 'ACCEPTED_COMMAND', command: RESOLVE_EFFECT_RULE },
    },
    {
      id: 'live-start-effect-resolved',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '第二回合 · LIVE 开始',
      title: 'LIVE 开始能力处理完毕',
      body: '点击下一步，按费用 9「钟岚珠」的 [BLADE] 3 公开 3 张应援牌，再进入判定。',
      pauseScript: true,
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.PHASE_CONTROLS },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'wait-second-judgment',
      contentVersion: 2,
      kind: 'OBSERVE',
      chapter: '第二回合 · LIVE 判定',
      title: '等待第二轮自动判定',
      body: '这次不再重复全部判定区说明；仍可核对成员 Heart、应援判心和必要 Heart。',
      statusText: '正在等待自动判定确认窗口',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.JUDGMENT_SUMMARY },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'ALL',
          conditions: [
            { kind: 'MATCH', subPhase: SubPhase.PERFORMANCE_JUDGMENT },
            { kind: 'COMMAND_AVAILABLE', commandType: GameCommandType.SUBMIT_JUDGMENT },
          ],
        },
      },
    },
    {
      id: 'accept-second-automatic-judgment',
      contentVersion: 2,
      kind: 'ACTION',
      chapter: '第二回合 · LIVE 判定',
      title: '接受第二轮自动判定',
      body: '核对结果后接受规则计算值。随后轮到对手表演，留意对手也会从卡组顶公开应援牌并接受自动判定。',
      statusText: '等待你确认第二轮自动判定',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.AUTOMATIC_JUDGMENT_CONFIRM,
        placement: 'TOP',
      },
      allowedCommands: [ACCEPT_AUTOMATIC_JUDGMENT_RULE, CONFIRM_JUDGMENT_SUBPHASE_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: ACCEPT_AUTOMATIC_JUDGMENT_RULE,
        additionalCommands: [CONFIRM_JUDGMENT_SUBPHASE_RULE],
      },
    },
    {
      id: 'observe-opponent-second-performance',
      contentVersion: 3,
      kind: 'OBSERVE',
      chapter: '第二回合 · 对手 LIVE',
      title: '观察对手的应援与自动判定',
      body: '对手的场攻估算是 7，看起来正好追平这张 LIVE 的合计需求；但它还指定需要[桃ハート][黄ハート][紫ハート]。这次舞台与实际公开的应援牌没有凑出[黄ハート]，实际 Heart 总数也不足，因此仍然判定失败。场攻适合快速估算，最后仍要核对颜色与真实判心。',
      statusText: '正在等待对手进入自动判定',
      completionDwellMs: 1_200,
      completionDwellStatusText: '对手的应援与判定已经显示，请看清后继续',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.OPPONENT_LIVE_ZONE },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'ALL',
          conditions: [
            {
              kind: 'MATCH',
              phase: GamePhase.PERFORMANCE_PHASE,
              subPhase: SubPhase.PERFORMANCE_JUDGMENT,
              activeSeat: 'OPPONENT',
            },
            {
              kind: 'OBJECT_IN_ZONE',
              role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.OPPONENT_SECOND_LIVE,
              seat: 'OPPONENT',
              zone: ZoneType.LIVE_ZONE,
            },
          ],
        },
      },
    },
    {
      id: 'wait-second-score',
      contentVersion: 2,
      kind: 'OBSERVE',
      chapter: '第二回合 · 结算',
      title: '进入第二轮分数确认',
      body: '对手接受自动判定并结束表演后，双方必要的成功效果窗口会按规则结束，再进入已经熟悉的分数确认。',
      statusText: '正在等待第二轮分数确认',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SCORE_CONFIRM },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'ALL',
          conditions: [
            { kind: 'MATCH', subPhase: SubPhase.RESULT_SCORE_CONFIRM },
            { kind: 'COMMAND_AVAILABLE', commandType: GameCommandType.SUBMIT_SCORE },
          ],
        },
      },
    },
    {
      id: 'confirm-second-score',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第二回合 · 结算',
      title: '确认第二轮分数',
      body: '确认规则计算的当前分数。',
      statusText: '等待第二轮分数确认',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SCORE_CONFIRM_ACTION },
      allowedCommands: [CONFIRM_COMPUTED_SCORE_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: CONFIRM_COMPUTED_SCORE_RULE,
        postCondition: { kind: 'LIVE_SCORE_CONFIRMED', seat: 'VIEWER' },
      },
    },
    {
      id: 'confirm-second-result',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第二回合 · 结算',
      title: '继续第二轮结算',
      body: '确认结果演出，进入成功 LIVE 选择。',
      statusText: '等待你继续结算',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.RESULT_ANIMATION_CONFIRM },
      allowedCommands: [CONFIRM_RESULT_ANIMATION_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: CONFIRM_RESULT_ANIMATION_RULE,
        postCondition: { kind: 'MATCH', subPhase: SubPhase.RESULT_SETTLEMENT },
      },
    },
    {
      id: 'select-effect-success-live',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第二回合 · 结算',
      title: '把特殊 LIVE 放入成功区',
      body: '选择这轮成功的高亮 LIVE。',
      statusText: '等待特殊 LIVE 进入成功区',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SUCCESS_LIVE_CANDIDATES },
      allowedCommands: [SELECT_EFFECT_SUCCESS_LIVE_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: SELECT_EFFECT_SUCCESS_LIVE_RULE,
        postCondition: {
          kind: 'OBJECT_IN_ZONE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.EFFECT_LIVE_CARD,
          seat: 'VIEWER',
          zone: ZoneType.SUCCESS_ZONE,
        },
      },
    },
    {
      id: 'confirm-second-settlement',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第二回合 · 结算',
      title: '结束第二轮 LIVE',
      body: '确认结算后，同一局会继续进入第三回合。',
      statusText: '等待第二轮结算完成',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.PHASE_PRIMARY_ACTION },
      allowedCommands: [CONFIRM_SETTLEMENT_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: CONFIRM_SETTLEMENT_RULE,
        postCondition: {
          kind: 'MATCH',
          excludedSubPhases: [SubPhase.RESULT_SETTLEMENT],
        },
      },
    },
    {
      id: 'third-turn-arrival',
      contentVersion: 1,
      kind: 'OBSERVE',
      chapter: '第三回合 · 资源回收',
      title: '第三回合抽到费用 2 回收成员',
      body: '仍然是同一局。第三回合的自动阶段完成后，费用 2「绚濑绘里」已经进入手牌。',
      statusText: '正在等待第三回合主要阶段',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.RECOVERY_MEMBER,
        placement: 'TOP',
      },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'ALL',
          conditions: [
            { kind: 'MATCH', phase: GamePhase.MAIN_PHASE, activeSeat: 'VIEWER' },
            {
              kind: 'OBJECT_IN_ZONE',
              role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.RECOVERY_MEMBER,
              seat: 'VIEWER',
              zone: ZoneType.HAND,
            },
          ],
        },
      },
    },
    {
      id: 'read-recovery-member',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '第三回合 · 资源回收',
      title: '低费用回收成员是常见资源循环',
      body: '费用 2「绚濑绘里」可以低成本登场。她的【起动】能力会把自己从舞台放置入休息室作为费用，再从自己的休息室把 1 张成员卡加入手牌。',
      mascot: 'READ_CARD',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.RECOVERY_MEMBER,
        placement: 'TOP',
      },
      secondaryTargets: [{ kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_WAITING_ROOM }],
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'play-recovery-member',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第三回合 · 资源回收',
      title: '让费用 2 成员登场到左侧',
      body: '把高亮成员拖到左侧舞台，或先选中她再点击高亮左侧区域。中央的费用 9 成员会保留。',
      statusText: '等待费用 2「绚濑绘里」登场到左侧',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.SELF_STAGE_LEFT,
        placement: 'TOP',
      },
      secondaryTargets: [
        {
          kind: 'OBJECT_ROLE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.RECOVERY_MEMBER,
        },
      ],
      allowedCommands: [PLAY_RECOVERY_MEMBER_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: PLAY_RECOVERY_MEMBER_RULE,
        postCondition: {
          kind: 'OBJECT_IN_ZONE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.RECOVERY_MEMBER,
          seat: 'VIEWER',
          zone: ZoneType.MEMBER_SLOT,
          slot: SlotPosition.LEFT,
        },
      },
    },
    {
      id: 'explain-activated-recovery',
      contentVersion: 1,
      kind: 'INFO',
      chapter: '第三回合 · 资源回收',
      title: '【起动】能力要由你主动发动',
      body: '【登场】和【LIVE开始时】会在对应事件发生后进入检查时点；【起动】则只会在合法主要阶段由玩家主动点击。发动后，冒号前的“将此成员放置入休息室”先作为费用支付。',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.RECOVERY_MEMBER,
        placement: 'TOP',
      },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'activate-recovery-member',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第三回合 · 资源回收',
      title: '发动费用 2 成员的回收能力',
      body: '点击高亮成员的能力按钮。规则会先把她从舞台放置入休息室，再打开合法回收目标的卡图选择。',
      statusText: '等待回收能力发动',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.RECOVERY_MEMBER,
        placement: 'TOP',
      },
      allowedCommands: [ACTIVATE_RECOVERY_MEMBER_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: ACTIVATE_RECOVERY_MEMBER_RULE,
        postCondition: {
          kind: 'OBJECT_IN_ZONE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.RECOVERY_MEMBER,
          seat: 'VIEWER',
          zone: ZoneType.WAITING_ROOM,
        },
      },
    },
    {
      id: 'explain-recovery-selection',
      contentVersion: 1,
      kind: 'INFO',
      chapter: '第三回合 · 资源回收',
      title: '费用已经支付，现在选择回收对象',
      body: '费用 4「桂城 泉」在第二回合换手时进入了休息室，现在可以被取回。休息室是公开区域，所选卡会先向双方短暂展示，再进入你的隐藏手牌。',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.ACTIVE_EFFECT_PANEL,
        placement: 'TOP',
      },
      secondaryTargets: [
        {
          kind: 'OBJECT_ROLE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.MEMBER_CARD,
        },
      ],
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'recover-original-member',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第三回合 · 资源回收',
      title: '选择费用 4「桂城 泉」加入手牌',
      body: '在效果面板中选择高亮的费用 4「桂城 泉」并确认。公开展示结束后，规则会把她加入手牌。',
      statusText: '等待选择、公开并回收费用 4「桂城 泉」',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.ACTIVE_EFFECT_CONFIRM,
        placement: 'TOP',
      },
      secondaryTargets: [
        { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.ACTIVE_EFFECT_SELECTION },
        {
          kind: 'OBJECT_ROLE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.MEMBER_CARD,
        },
      ],
      allowedCommands: [RESOLVE_EFFECT_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: RESOLVE_EFFECT_RULE,
        postCondition: {
          kind: 'OBJECT_IN_ZONE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.MEMBER_CARD,
          seat: 'VIEWER',
          zone: ZoneType.HAND,
        },
      },
    },
    {
      id: 'recovery-energy-window',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '第三回合 · 资源回收',
      title: '剩余能量可以继续在本回合使用',
      body: '本回合共有 6 点活跃能量。费用 2「绚濑绘里」登场后还剩 4 点；发动回收能力不支付能量，因此这 4 点剩余能量可继续用来让刚回到手牌的费用 4「桂城 泉」登场。',
      mascot: 'READ_CARD',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_ENERGY_ZONE },
      secondaryTargets: [
        {
          kind: 'OBJECT_ROLE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.MEMBER_CARD,
          padding: 8,
        },
        { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_STAGE_LEFT },
      ],
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'replay-recovered-member',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第三回合 · 资源回收',
      title: '用剩余 4 点能量让桂城 泉再次登场',
      body: '先选中高亮的费用 4「桂城 泉」，再点击左侧舞台；也可以直接拖到高亮区域。规则会把剩余 4 点活跃能量全部用于支付。',
      statusText: '等待费用 4「桂城 泉」重新登场到左侧',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.SELF_STAGE_LEFT,
        placement: 'TOP',
      },
      secondaryTargets: [
        {
          kind: 'OBJECT_ROLE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.MEMBER_CARD,
          padding: 8,
        },
        { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_ENERGY_ZONE },
      ],
      allowedCommands: [REPLAY_RECOVERED_MEMBER_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: REPLAY_RECOVERED_MEMBER_RULE,
        postCondition: {
          kind: 'OBJECT_IN_ZONE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.MEMBER_CARD,
          seat: 'VIEWER',
          zone: ZoneType.MEMBER_SLOT,
          slot: SlotPosition.LEFT,
        },
      },
    },
    {
      id: 'end-third-main',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第三回合 · 对手回应',
      title: '结束主要阶段，把操作权交给对手',
      body: '回收的成员已经再次登场，6 点能量也刚好全部使用。点击阶段按钮结束自己的主要阶段，观察对手如何用换手与补员继续提高场攻。',
      statusText: '等待第三回合主要阶段结束',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.PHASE_PRIMARY_ACTION },
      allowedCommands: [END_MAIN_PHASE_RULE],
      completion: { kind: 'ACCEPTED_COMMAND', command: END_MAIN_PHASE_RULE },
    },
    {
      id: 'opponent-third-relay',
      contentVersion: 2,
      kind: 'OBSERVE',
      chapter: '第三回合 · 对手回应',
      title: '对手也用换手强化中央',
      body: '费用 9「星空凛」替换中央的费用 7「东条希」，换手后只需支付 2 点能量。中央成员继续从 3 Heart、2 个 [BLADE] 提升为 4 Heart、3 个 [BLADE]。',
      statusText: '正在观察对手的换手登场',
      completionDwellMs: 1_200,
      completionDwellStatusText: '对手已经完成中央换手',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.OPPONENT_STAGE_CENTER },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'OBJECT_IN_ZONE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.OPPONENT_FINAL_RELAY_MEMBER,
          seat: 'OPPONENT',
          zone: ZoneType.MEMBER_SLOT,
          slot: SlotPosition.CENTER,
        },
      },
    },
    {
      id: 'opponent-third-turn',
      contentVersion: 3,
      kind: 'OBSERVE',
      chapter: '第三回合 · 对手回应',
      title: '再用剩余能量补满右侧',
      body: '换手支付 2 点后，对手还有 4 点活跃能量，刚好让费用 4「园田海未」登场到右侧。三个成员合计 7 Heart、5 个 [BLADE]，估算场攻从上一回合的 7 提高到了 12。',
      statusText: '正在观察对手的成员登场',
      completionDwellMs: 1_200,
      completionDwellStatusText: '对手已经完成成员登场',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.OPPONENT_STAGE_RIGHT },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'OBJECT_IN_ZONE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.OPPONENT_THIRD_MEMBER,
          seat: 'OPPONENT',
          zone: ZoneType.MEMBER_SLOT,
          slot: SlotPosition.RIGHT,
        },
      },
    },
    {
      id: 'final-chapter-welcome',
      contentVersion: 1,
      kind: 'INFO',
      chapter: '第四章 · 制胜规划',
      title: '还差 1 张成功 LIVE 就能获胜',
      body: '成功 LIVE 区已经有 2 张卡。下一轮不再只照着高亮操作：先计算舞台成员稳定提供的 Heart，再判断手牌中的哪些 LIVE 值得一起设置。',
      mascot: 'WELCOME',
      pauseScript: true,
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_SUCCESS_LIVE_ZONE },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'wait-final-live-set',
      contentVersion: 1,
      kind: 'OBSERVE',
      chapter: '第四章 · 制胜规划',
      title: '对手结束主要阶段，进入 LIVE 设置',
      body: '对手的舞台配置已经完成。接下来轮到你根据现有成员与手牌规划这次表演。',
      statusText: '正在等待 LIVE 设置阶段',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.PHASE_CONTROLS },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'ALL',
          conditions: [
            {
              kind: 'MATCH',
              phase: GamePhase.LIVE_SET_PHASE,
              subPhase: SubPhase.LIVE_SET_FIRST_PLAYER,
              activeSeat: 'VIEWER',
            },
            { kind: 'COMMAND_AVAILABLE', commandType: GameCommandType.SET_LIVE_CARD },
          ],
        },
      },
    },
    {
      id: 'count-final-stage-hearts',
      contentVersion: 3,
      kind: 'INFO',
      chapter: '第四章 · 计算场攻',
      title: '5 Heart + 4 判 = 9 只是场攻估算',
      body: '左侧成员提供 [桃ハート][紫ハート]与 1 个 [BLADE]，中央成员提供 [桃ハート][黄ハート][緑ハート]与 3 个 [BLADE]。成员 Heart 是 5，BLADE 判数是 4，所以当前场攻通常按 5 + 4 = 9 估算。不过，[BLADE] 只决定公开几张应援牌，不保证每张都有 Heart。',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_STAGE_CENTER },
      secondaryTargets: [{ kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_STAGE_LEFT }],
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'compare-final-live-options',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '第四章 · 比较 LIVE',
      title: '把准备设置的 LIVE 需求合起来算',
      body: '分数 1 LIVE 需要合计 4 Heart，分数 2 LIVE 需要 [黄ハート][紫ハート]且合计 5 Heart；两张一起就是 9 Heart。如果 4 张判定牌都带有 Heart，就能刚好满足。分数 3 LIVE 还需要 [赤ハート][青ハート]且合计 7 Heart，不适合再加入这次配置。',
      mascot: 'READ_CARD',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.FINAL_LIVE_TWO,
        placement: 'TOP',
      },
      secondaryTargets: [
        { kind: 'OBJECT_ROLE', role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.FINAL_LIVE_ONE },
        { kind: 'OBJECT_ROLE', role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.FINAL_LIVE_RISKY },
      ],
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'set-final-live-one',
      contentVersion: 2,
      kind: 'ACTION',
      chapter: '第四章 · 配置 LIVE',
      title: '先设置需要 4 Heart 的分数 1 LIVE',
      body: '把高亮的分数 1 LIVE 盖到 LIVE 区。它的必要 Heart 合计为 4，会计入本轮所有已设置 LIVE 的合并需求。',
      statusText: '等待分数 1 LIVE 进入 LIVE 区',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.FINAL_LIVE_ONE,
        placement: 'TOP',
      },
      secondaryTargets: [{ kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_LIVE_ZONE }],
      allowedCommands: [SET_FINAL_LIVE_ONE_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: SET_FINAL_LIVE_ONE_RULE,
        postCondition: {
          kind: 'OBJECT_IN_ZONE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.FINAL_LIVE_ONE,
          seat: 'VIEWER',
          zone: ZoneType.LIVE_ZONE,
        },
      },
    },
    {
      id: 'set-final-live-two',
      contentVersion: 2,
      kind: 'ACTION',
      chapter: '第四章 · 配置 LIVE',
      title: '再设置需要 5 Heart 的分数 2 LIVE',
      body: '继续把高亮的分数 2 LIVE 盖到 LIVE 区。两张 LIVE 的合计需求来到 9，等于 5 个成员 Heart 加 4 判的估算值；实际能否满足，仍取决于公开的判心。',
      statusText: '等待分数 2 LIVE 进入 LIVE 区',
      target: {
        kind: 'OBJECT_ROLE',
        role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.FINAL_LIVE_TWO,
        placement: 'TOP',
      },
      secondaryTargets: [{ kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_LIVE_ZONE }],
      allowedCommands: [SET_FINAL_LIVE_TWO_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: SET_FINAL_LIVE_TWO_RULE,
        postCondition: {
          kind: 'OBJECT_IN_ZONE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.FINAL_LIVE_TWO,
          seat: 'VIEWER',
          zone: ZoneType.LIVE_ZONE,
        },
      },
    },
    {
      id: 'review-final-live-plan',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '第四章 · 配置 LIVE',
      title: '这是一手刚好卡 9 的尝试',
      body: '两张已设置 LIVE 的必要 Heart 会合并为 9。4 个 [BLADE] 不一定都能翻到 Heart，所以这次表演仍可能失败——但还差 1 张成功 LIVE 就能获胜，值得赌一把。要求 7 Heart 且缺少红、蓝指定色的分数 3 LIVE 继续留在手牌。',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_LIVE_ZONE },
      secondaryTargets: [
        { kind: 'OBJECT_ROLE', role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.FINAL_LIVE_RISKY },
      ],
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'confirm-final-live-set',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第四章 · 配置 LIVE',
      title: '确认这次的 LIVE 配置',
      body: '确认后会轮到对手盖牌。两张已设置的 LIVE 会保持里侧，直到表演开始。',
      statusText: '等待确认 LIVE 配置',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.PHASE_PRIMARY_ACTION },
      allowedCommands: [CONFIRM_LIVE_SET_RULE],
      completion: { kind: 'ACCEPTED_COMMAND', command: CONFIRM_LIVE_SET_RULE },
    },
    {
      id: 'opponent-final-live-set',
      contentVersion: 2,
      kind: 'OBSERVE',
      chapter: '第四章 · 对手设置',
      title: '对手也盖下了最后一轮 LIVE',
      body: '双方再次完成 LIVE 设置。里侧期间仍然不能提前查看对手的卡；你的两张 LIVE 会先公开并共用本次 Heart，随后对手也会进行自己的表演与判定。',
      statusText: '正在等待对手完成 LIVE 设置',
      completionDwellMs: 1_200,
      completionDwellStatusText: '双方已经盖好 LIVE，最终对决即将开始',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.OPPONENT_LIVE_ZONE },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'ALL',
          conditions: [
            {
              kind: 'MATCH',
              phase: GamePhase.LIVE_SET_PHASE,
              subPhase: SubPhase.LIVE_SET_SECOND_PLAYER,
            },
            {
              kind: 'ZONE_CARD_COUNT',
              seat: 'OPPONENT',
              zone: ZoneType.LIVE_ZONE,
              minimumCount: 1,
            },
          ],
        },
      },
    },
    {
      id: 'wait-final-judgment',
      contentVersion: 3,
      kind: 'OBSERVE',
      chapter: '第四章 · 制胜表演',
      title: '公开两张制胜 LIVE，进入自动判定',
      body: '规则会按 4 个 [BLADE] 从主卡组顶公开 4 张应援牌。先看实际判心能不能补足成员 Heart 之外的 4 Heart。',
      statusText: '正在等待制胜 LIVE 的判定窗口',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.JUDGMENT_SUMMARY },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'ALL',
          conditions: [
            { kind: 'MATCH', subPhase: SubPhase.PERFORMANCE_JUDGMENT },
            { kind: 'COMMAND_AVAILABLE', commandType: GameCommandType.SUBMIT_JUDGMENT },
          ],
        },
      },
    },
    {
      id: 'read-final-judgment',
      contentVersion: 2,
      kind: 'INFO',
      chapter: '第四章 · 制胜表演',
      title: '太好了，必要 Heart 全部满足了！',
      body: '判定区公开的 4 张卡全都带有 Heart 判心。成员 5 Heart 加上 4 张判心，刚好满足两张 LIVE 合计需要的 9 Heart。',
      mascot: 'CELEBRATE',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.JUDGMENT_SUMMARY },
      completion: { kind: 'INFO_CONTINUE' },
    },
    {
      id: 'accept-final-automatic-judgment',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第四章 · 制胜表演',
      title: '接受制胜表演的自动判定',
      body: '核对两张 LIVE 的结果后，接受规则计算值。',
      statusText: '等待确认制胜 LIVE 的自动判定',
      target: {
        kind: 'ANCHOR',
        anchor: BATTLE_UI_ANCHORS.AUTOMATIC_JUDGMENT_CONFIRM,
        placement: 'TOP',
      },
      allowedCommands: [ACCEPT_AUTOMATIC_JUDGMENT_RULE, CONFIRM_JUDGMENT_SUBPHASE_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: ACCEPT_AUTOMATIC_JUDGMENT_RULE,
        additionalCommands: [CONFIRM_JUDGMENT_SUBPHASE_RULE],
      },
    },
    {
      id: 'observe-opponent-final-performance',
      contentVersion: 3,
      kind: 'OBSERVE',
      chapter: '第四章 · 对手 LIVE',
      title: '对手也把积累的场攻用起来了',
      body: '对手已经把估算场攻积累到 12。现在公开的分数 2 LIVE 需要[桃ハート][紫ハート]与合计 5 Heart，光靠舞台成员就已经满足，因此这次会稳定成功；不过你的两张 LIVE 合计 3 分，仍高于对手的 2 分。',
      statusText: '正在观察对手的最终应援与判定',
      completionDwellMs: 1_200,
      completionDwellStatusText: '对手的 LIVE 判定已经显示',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.OPPONENT_LIVE_ZONE },
      secondaryTargets: [
        { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.OPPONENT_STAGE_LEFT },
        { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.OPPONENT_STAGE_CENTER },
        { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.OPPONENT_STAGE_RIGHT },
      ],
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'ALL',
          conditions: [
            {
              kind: 'MATCH',
              phase: GamePhase.PERFORMANCE_PHASE,
              subPhase: SubPhase.PERFORMANCE_JUDGMENT,
              activeSeat: 'OPPONENT',
            },
            {
              kind: 'OBJECT_IN_ZONE',
              role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.OPPONENT_FINAL_LIVE,
              seat: 'OPPONENT',
              zone: ZoneType.LIVE_ZONE,
            },
          ],
        },
      },
    },
    {
      id: 'wait-final-score',
      contentVersion: 2,
      kind: 'OBSERVE',
      chapter: '第四章 · 最终结算',
      title: '双方都成功，进入最终计分',
      body: '对手接受自动判定后，规则会比较双方分数：你的两张 LIVE 合计 3 分，对手是 2 分，因此本轮由你取得成功 LIVE 选择权。',
      statusText: '正在等待最终分数确认',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SCORE_CONFIRM },
      completion: {
        kind: 'VIEW_STATE',
        condition: {
          kind: 'ALL',
          conditions: [
            { kind: 'MATCH', subPhase: SubPhase.RESULT_SCORE_CONFIRM },
            { kind: 'COMMAND_AVAILABLE', commandType: GameCommandType.SUBMIT_SCORE },
          ],
        },
      },
    },
    {
      id: 'confirm-final-score',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第四章 · 最终结算',
      title: '确认最终分数',
      body: '确认两张成功 LIVE 合计得到的规则分数。',
      statusText: '等待最终分数确认',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SCORE_CONFIRM_ACTION },
      allowedCommands: [CONFIRM_COMPUTED_SCORE_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: CONFIRM_COMPUTED_SCORE_RULE,
        postCondition: { kind: 'LIVE_SCORE_CONFIRMED', seat: 'VIEWER' },
      },
    },
    {
      id: 'confirm-final-result-animation',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第四章 · 最终结算',
      title: '确认最终结果',
      body: '确认结果演出，进入本轮成功 LIVE 选择。',
      statusText: '等待最终结果确认',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.RESULT_ANIMATION_CONFIRM },
      allowedCommands: [CONFIRM_RESULT_ANIMATION_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: CONFIRM_RESULT_ANIMATION_RULE,
        postCondition: { kind: 'MATCH', subPhase: SubPhase.RESULT_SETTLEMENT },
      },
    },
    {
      id: 'select-final-success-live',
      contentVersion: 1,
      kind: 'ACTION',
      chapter: '第四章 · 最终结算',
      title: '选择第三张成功 LIVE',
      body: '两张 LIVE 都成功，但每轮只能选择其中 1 张进入成功 LIVE 区。选择高亮的分数 2 LIVE；成功 LIVE 达到 3 张后，对局会立即结束。',
      statusText: '等待选择第三张成功 LIVE',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SUCCESS_LIVE_CANDIDATES },
      secondaryTargets: [
        { kind: 'OBJECT_ROLE', role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.FINAL_LIVE_TWO },
      ],
      allowedCommands: [SELECT_FINAL_SUCCESS_LIVE_RULE],
      completion: {
        kind: 'ACCEPTED_COMMAND',
        command: SELECT_FINAL_SUCCESS_LIVE_RULE,
        postCondition: {
          kind: 'OBJECT_IN_ZONE',
          role: BASIC_LIVE_TUTORIAL_OBJECT_ROLES.FINAL_LIVE_TWO,
          seat: 'VIEWER',
          zone: ZoneType.SUCCESS_ZONE,
        },
      },
    },
    {
      id: 'complete',
      contentVersion: 5,
      kind: 'INFO',
      chapter: '完成',
      title: '漂亮！你用自己的规划赢下了对局',
      body: '你已经学会估算当前场攻、核对 LIVE 的指定颜色与合计需求，并在明白判心风险的前提下做出制胜配置，拿到第三张成功 LIVE。',
      mascot: 'CELEBRATE',
      continueLabel: '完成教程',
      target: { kind: 'ANCHOR', anchor: BATTLE_UI_ANCHORS.SELF_SUCCESS_LIVE_ZONE },
      completion: { kind: 'INFO_CONTINUE' },
    },
  ],
};
