import * as abilityIds from './ability-ids.js';

export type LegacyPersistedBladeScope = 'SOURCE_MEMBER' | 'TARGET_MEMBER' | 'PLAYER' | 'AMBIGUOUS';

export type LegacyPersistedBladeTargetStorage = 'SOURCE_CARD_ID' | 'TARGET_MEMBER_CARD_ID';

type LegacyPersistedBladeScopeEntry =
  | readonly [string, Exclude<LegacyPersistedBladeScope, 'TARGET_MEMBER'>]
  | readonly [string, 'TARGET_MEMBER', LegacyPersistedBladeTargetStorage];

export interface LegacyPersistedBladeAudit {
  readonly scope: LegacyPersistedBladeScope;
  readonly targetStorage?: LegacyPersistedBladeTargetStorage;
}

/**
 * Frozen compatibility table for GAME_STATE_V1 BLADE modifiers that did not
 * persist an explicit target. Every entry was classified from its card text
 * and workflow; callers must never infer scope from sourceCardId or card type.
 *
 * TARGET_MEMBER also freezes whether the historical workflow stored its
 * beneficiary in sourceCardId or in targetMemberCardId. AMBIGUOUS means one
 * ability historically emitted more than one scope with the same abilityId,
 * so a targetless payload cannot be migrated safely.
 */
const LEGACY_PERSISTED_BLADE_SCOPE_ENTRIES = [
  [abilityIds.LL_BP2_001_LIVE_START_DISCARD_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.BP3_006_LIVE_START_DISCARD_GAIN_BLADE_BY_SUCCESS_COUNT_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.BP4_010_LIVE_START_PAY_ENERGY_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.BP6_006_ACTIVATED_DISCARD_CHOOSE_COLOR_REVEAL_FIVE_MUSE_HAND_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.HS_BP1_004_LIVE_START_PAY_ENERGY_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.HS_BP2_005_LIVE_START_PAY_ENERGY_FULL_STAGE_GAIN_TWO_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [
    abilityIds.HS_BP2_008_ON_ENTER_LOWER_COST_DOLLCHESTRA_RELAY_GAIN_TWO_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.HS_BP5_001_ON_ENTER_MILL_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.HS_BP5_013_LIVE_START_MILL_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.HS_BP5_014_AUTO_ON_MOVE_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.HS_BP6_004_LIVE_START_DISCARD_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.HS_BP6_005_LIVE_START_DISCARD_GAIN_COST_CONDITIONAL_BLUE_HEART_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [
    abilityIds.HS_BP6_009_LIVE_START_MILL_FOUR_ALL_HASUNOSORA_GAIN_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.HS_BP8_001_AUTO_WAITING_ROOM_TO_DECK_GAIN_THREE_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.HS_CL1_006_ON_ENTER_GAIN_THREE_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.HS_PB1_001_LIVE_START_PAY_TWO_ENERGY_GAIN_GREEN_HEART_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.HS_PB1_003_AUTO_HAND_TO_WAITING_GAIN_HEART_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.HS_PB1_005_LIVE_START_CHOOSE_NUMBER_REVEAL_TOP_HAND_OR_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [
    abilityIds.HS_PB1_006_LIVE_START_POSITION_CHANGE_TO_OTHER_MIRACRA_GAIN_HEART_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.HS_PB1_009_ON_HASUNOSORA_ENTER_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.HS_PB1_012_ON_ENTER_RECYCLE_MEMBERS_RECOVER_LIVE_GAIN_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.HS_PR_001_LIVE_START_PAY_TWO_ENERGY_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.HS_PR_016_LIVE_START_DISCARD_SAME_UNIT_GAIN_GREEN_HEART_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [
    abilityIds.HS_PR_017_LIVE_START_DISCARD_SAME_UNIT_GAIN_BLUE_HEART_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [
    abilityIds.HS_SD1_002_LIVE_START_DISCARD_TWO_LOOK_TOP_MEMBER_HAND_GAIN_HEART_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.HS_SD1_006_LIVE_START_PAY_ENERGY_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.N_BP1_005_LIVE_START_DISCARD_GAIN_ONE_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.N_BP5_015_LIVE_START_ALL_SIX_STAGE_HEARTS_GAIN_TWO_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.N_BP7_003_LIVE_START_DIFFERENT_MEMBER_BELOW_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.N_BP7_006_ACTIVATED_MILL_TOP_THREE_CHOOSE_ENERGY_OR_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.N_SD1_004_LIVE_START_DISCARD_GAIN_TWO_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.N_SD2_004_LIVE_START_PAY_ENERGY_GAIN_TWO_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.N_SD2_006_LIVE_START_WAIT_NIJIGASAKI_MEMBER_GAIN_TWO_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.N_SD2_008_LIVE_START_PAY_ENERGY_GAIN_TWO_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.PL_N_BP1_001_LIVE_START_PAY_ONE_ENERGY_GAIN_ONE_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.PL_N_BP3_011_ON_ENTER_COMPARE_OPPONENT_MEMBER_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.PL_S_BP5_009_ON_ENTER_PAY_ENERGY_RECOVER_SAINTSNOW_GAIN_TWO_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [
    abilityIds.PL_S_PB1_006_ACTIVATED_REVEAL_HAND_LIVE_OPPONENT_DISCARD_OR_GAIN_FOUR_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.S_BP3_003_LIVE_START_DISCARD_UP_TO_TWO_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.S_BP5_016_LIVE_START_HIGHER_COST_THAN_ALL_OPPONENT_STAGE_GAIN_TWO_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [
    abilityIds.S_BP6_006_ON_ENTER_DRAW_TWO_FROM_WAITING_GAIN_THREE_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.S_BP6_013_ON_ENTER_GAIN_TWO_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.S_BP7_001_ON_ENTER_DISCARD_RECOVER_HIGH_COST_MEMBER_GAIN_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.S_BP7_007_LIVE_START_BOTTOM_AQOURS_MEMBERS_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.S_PR_013_LIVE_START_PAY_TWO_ENERGY_GAIN_TWO_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.S_PR_016_ON_ENTER_GAIN_ONE_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.S_SD1_009_LIVE_START_REVEAL_AQOURS_HAND_TOP_BOTTOM_GAIN_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.SP_BP2_009_LIVE_START_HAND_COUNT_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.SP_BP4_017_LIVE_START_LEFT_MOVED_GAIN_TWO_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.SP_BP4_020_LIVE_START_RIGHT_MOVED_GAIN_TWO_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.SP_BP4_022_LIVE_START_PAY_UP_TO_TWO_ENERGY_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.SP_BP5_002_ACTIVATED_WAIT_DRAW_THREE_DISCARD_TWO_NO_BLADE_HEART_REWARD_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [
    abilityIds.SP_BP5_005_ACTIVATED_MILL_THREE_GAIN_BLADE_BY_LIELLA_MEMBER_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [
    abilityIds.SP_BP5_009_LIVE_START_REPEAT_MILL_GAIN_BLADE_WAIT_IF_LIVE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.SP_BP5_015_ON_ENTER_CENTER_GAIN_TWO_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.SP_BP7_004_LIVE_START_BOTTOM_THREE_LIELLA_MEMBERS_GAIN_TWO_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.SP_BP7_005_AUTO_OWN_EFFECT_PLACE_ENERGY_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.SP_BP7_007_LIVE_START_RETURN_TWO_GAIN_THREE_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.SP_BP7_014_AUTO_ON_MOVE_GAIN_TWO_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.SP_PB1_006_AUTO_ENTER_OR_MOVE_GAIN_TWO_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.SP_PB2_000_ON_ENTER_DOUBLE_RELAY_DRAW_AND_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [
    abilityIds.SP_PB2_011_AUTO_CENTER_MEMBER_MOVED_CHOOSE_BLADE_WAIT_OR_DRAW_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [
    abilityIds.SP_PB2_022_AUTO_5YNCRISE_MEMBER_MOVED_CENTER_GAIN_FOUR_BLADE_ABILITY_ID,
    'SOURCE_MEMBER',
  ],
  [abilityIds.SP_PB2_040_LIVE_START_PAY_ENERGY_GAIN_TWO_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.SP_PR_LIVE_START_DISCARD_GAIN_BLADE_DRAW_IF_LIVE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.SP_SD1_003_LIVE_START_DISCARD_TWO_GAIN_FIVE_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],
  [abilityIds.SP_SD2_011_AUTO_ON_MOVE_GAIN_BLADE_ABILITY_ID, 'SOURCE_MEMBER'],

  [
    abilityIds.BP4_017_LIVE_START_WAIT_SELF_CENTER_MUSE_GAIN_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.BP6_001_LIVE_START_CENTER_MUSE_LIVE_STAGE_MUSE_MEMBERS_GAIN_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.HS_BP2_007_LIVE_START_DISCARD_MEMBER_TARGET_SAME_NAME_GREEN_HEART_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.HS_BP6_014_ACTIVATED_HAND_DISCARD_SELF_DRAW_TARGET_MEGU_RURINO_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.HS_BP6_018_LEAVE_STAGE_DISCARD_TARGET_BLUE_HEART_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.HS_BP6_031_LIVE_START_RECYCLE_MIRACRA_MEMBERS_GAIN_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.HS_CL1_003_ACTIVATED_WAIT_SELF_MIRACRA_MEMBER_GAIN_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.HS_CL1_010_LIVE_START_HIGH_COST_HASUNOSORA_MEMBER_GAIN_TWO_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.HS_PB1_030_LIVE_START_EDELNOTE_MEMBER_BLADE_DIFFERENT_NAME_PURPLE_HEART_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.HS_SD1_003_LIVE_START_PAY_ENERGY_TARGET_OTHER_HASUNOSORA_HEART_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.HS_SD1_020_LIVE_START_DISCARD_UP_TO_THREE_HASUNOSORA_MEMBERS_TARGET_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.N_BP7_025_LIVE_START_TARGET_NIJIGASAKI_MEMBER_GAIN_ONE_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'TARGET_MEMBER_CARD_ID',
  ],
  [
    abilityIds.N_BP7_026_LIVE_START_DISCARD_UP_TO_TWO_TARGET_NIJIGASAKI_GAIN_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'TARGET_MEMBER_CARD_ID',
  ],
  [
    abilityIds.N_SD1_001_LIVE_START_PAY_ONE_ENERGY_OTHER_NIJIGASAKI_MEMBERS_GAIN_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.PL_BP3_026_LIVE_START_DISCARD_TWO_TARGET_MEMBER_GAIN_THREE_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.PL_BP4_011_LIVE_START_WAIT_SELF_CENTER_MUSE_GAIN_TWO_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.PL_BP4_014_LIVE_START_LIVE_WITHOUT_TIMING_TARGET_OTHER_MEMBER_GAIN_TWO_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'TARGET_MEMBER_CARD_ID',
  ],
  [
    abilityIds.PL_BP4_024_LIVE_START_TARGET_MUSE_MEMBER_GAIN_ONE_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'TARGET_MEMBER_CARD_ID',
  ],
  [
    abilityIds.PL_BP5_024_LIVE_START_PRIVATE_WARS_CHOICE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.PL_N_BP3_001_LIVE_START_STACK_ENERGY_DRAW_STAGE_GAIN_TWO_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.PL_N_BP4_026_AUTO_FACE_UP_LIVE_ZONE_NIJIGASAKI_MEMBER_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.PL_N_BP4_029_LIVE_START_TURN_ONE_SCORE_TARGET_NIJIGASAKI_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.PL_N_PB1_003_ACTIVATED_PAY_TWO_ENERGY_HAND_DISCARD_SELF_DRAW_TARGET_NIJIGASAKI_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.PL_PB1_010_LIVE_START_DISCARD_HAND_OTHER_MEMBERS_GAIN_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.PL_S_BP5_004_ON_ENTER_CHOOSE_AQOURS_BLADE_OR_SAINTSNOW_POSITION_CHANGE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.PR_AUTO_RELAY_REPLACEMENT_COST_NINE_GAIN_TWO_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'TARGET_MEMBER_CARD_ID',
  ],
  [
    abilityIds.S_BP2_023_LIVE_START_OTHER_AQOURS_LIVE_STAGE_MEMBERS_GAIN_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.S_BP2_025_LIVE_START_SUCCESS_TWO_TARGET_MEMBER_GAIN_TWO_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'TARGET_MEMBER_CARD_ID',
  ],
  [
    abilityIds.S_BP3_021_LIVE_START_WAITING_MEMBER_TO_DECK_TOP_GRANT_STAGE_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.S_BP3_024_LIVE_START_CENTER_HIGH_COST_AQOURS_CHOOSE_BLADE_OR_WAIT_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.S_BP5_022_LIVE_START_MOVED_STAGE_MEMBERS_GAIN_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.S_SD1_022_LIVE_START_AQOURS_STAGE_MEMBERS_GAIN_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.SP_BP1_024_LIVE_START_KANON_KEKE_GAIN_HEART_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.SP_BP4_023_LIVE_START_SELECT_NAMED_AND_OTHER_LIELLA_GAIN_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.SP_BP4_024_LIVE_START_LEFT_LIELLA_RED_HEART_THREE_GAIN_TWO_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],
  [
    abilityIds.SP_BP7_025_LIVE_START_TARGET_CHISATO_GAIN_ONE_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'TARGET_MEMBER_CARD_ID',
  ],
  [
    abilityIds.SP_BP7_028_LIVE_START_BOTTOM_NINE_LIELLA_MEMBERS_ALL_STAGE_GAIN_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'TARGET_MEMBER_CARD_ID',
  ],
  [
    abilityIds.SP_SD2_025_LIVE_START_MOVED_LIELLA_MEMBERS_GAIN_BLADE_ABILITY_ID,
    'TARGET_MEMBER',
    'SOURCE_CARD_ID',
  ],

  [
    abilityIds.SP_SD2_020_LIVE_START_ENERGY_SEVEN_SOURCE_AND_OTHER_LIELLA_GAIN_BLADE_ABILITY_ID,
    'AMBIGUOUS',
  ],
] as const satisfies readonly LegacyPersistedBladeScopeEntry[];

const LEGACY_PERSISTED_BLADE_AUDIT_BY_ABILITY_ID = new Map<string, LegacyPersistedBladeAudit>(
  LEGACY_PERSISTED_BLADE_SCOPE_ENTRIES.map(([abilityId, scope, targetStorage]) => [
    abilityId,
    targetStorage === undefined ? { scope } : { scope, targetStorage },
  ])
);

if (
  LEGACY_PERSISTED_BLADE_AUDIT_BY_ABILITY_ID.size !== LEGACY_PERSISTED_BLADE_SCOPE_ENTRIES.length
) {
  throw new Error('legacy persisted BLADE scope table contains duplicate abilityIds');
}

for (const [, scope, targetStorage] of LEGACY_PERSISTED_BLADE_SCOPE_ENTRIES) {
  if (
    (scope === 'TARGET_MEMBER' && targetStorage === undefined) ||
    (scope !== 'TARGET_MEMBER' && targetStorage !== undefined)
  ) {
    throw new Error('legacy persisted BLADE target storage does not match scope');
  }
}

export function getLegacyPersistedBladeAudit(
  abilityId: string
): LegacyPersistedBladeAudit | undefined {
  return LEGACY_PERSISTED_BLADE_AUDIT_BY_ABILITY_ID.get(abilityId);
}

export function getLegacyPersistedBladeScope(
  abilityId: string
): LegacyPersistedBladeScope | undefined {
  return getLegacyPersistedBladeAudit(abilityId)?.scope;
}

export function getLegacyPersistedBladeScopeEntries(): readonly LegacyPersistedBladeScopeEntry[] {
  return LEGACY_PERSISTED_BLADE_SCOPE_ENTRIES;
}
