import { describe, expect, it } from 'vitest';
import { createCardInstance, createHeartIcon, createHeartRequirement, type CardInstance, type MemberCardData } from '../../src/domain/entities/card';
import { createGameState, registerCards, updatePlayer, type PendingAbilityState } from '../../src/domain/entities/game';
import { placeCardInSlot } from '../../src/domain/entities/zone';
import { confirmActiveEffectStep, resolvePendingCardEffects } from '../../src/application/card-effect-runner';
import { createConfirmEffectStepCommand } from '../../src/application/game-commands';
import { createGameSession } from '../../src/application/game-session';
import { getCardAbilityDefinitionsForCardCode } from '../../src/application/card-effects/definitions/lookup';
import { PL_N_BP3_028_LIVE_START_LOOK_TOP_PER_NIJIGASAKI_REVEAL_LIVE_SCORE_ABILITY_ID as ABILITY } from '../../src/application/card-effects/ability-ids';
import { SP_BP5_005_AUTO_MAIN_PHASE_CARD_ENTER_WAITING_ROOM_PAY_ENERGY_RECOVER_ABILITY_ID as PROVING } from '../../src/application/card-effects/ability-ids';
import { CardType, FaceState, GamePhase, HeartColor, OrientationState, SlotPosition, TriggerCondition, ZoneType } from '../../src/shared/types/enums';
const P1='p1',P2='p2';
function member(id:string,group='虹ヶ咲',owner=P1):CardInstance<MemberCardData>{return createCardInstance({cardCode:id,name:id,cardType:CardType.MEMBER,cost:1,blade:1,groupNames:[group],hearts:[createHeartIcon(HeartColor.PINK,1)]},owner,id);}
function live(id:string){return createCardInstance({cardCode:id,name:id,cardType:CardType.LIVE,score:1,requirements:createHeartRequirement({[HeartColor.PINK]:1})},P1,id);}
function setup(stage=1,topLive=true){const source=live('PL!N-bp3-028-L'),top=topLive?live('top'):member('top'),rest=member('rest'),members=[member('m1'),member('m2'),member('m3')];let game=createGameState('connect',P1,'P1',P2,'P2');game=registerCards(game,[source,top,rest,...members]);game=updatePlayer(game,P1,p=>({...p,liveZone:{...p.liveZone,cardIds:[source.instanceId]},mainDeck:{...p.mainDeck,cardIds:[top.instanceId,rest.instanceId]},memberSlots:members.slice(0,stage).reduce((z,c,i)=>placeCardInSlot(z,[SlotPosition.CENTER,SlotPosition.LEFT,SlotPosition.RIGHT][i]!,c.instanceId,{orientation:i===1?OrientationState.WAITING:OrientationState.ACTIVE,face:FaceState.FACE_UP}),p.memberSlots)}));const pending:PendingAbilityState={id:'pending',abilityId:ABILITY,sourceCardId:source.instanceId,controllerId:P1,mandatory:true,timingId:TriggerCondition.ON_LIVE_START,eventIds:[]};return {game:{...game,pendingAbilities:[pending]},source,top,rest};}
function start(g:ReturnType<typeof setup>['game']){return resolvePendingCardEffects(g).gameState;} function confirm(g:ReturnType<typeof setup>['game'],ids:string[]=[]){return confirmActiveEffectStep(g,P1,g.activeEffect!.id,undefined,undefined,undefined,undefined,ids);}
describe('PL!N-bp3-028 ツナガルコネクト',()=>{
 it.each(['PL!N-bp3-028-L','PL!N-bp3-028-SECL'])('shares the implemented base definition for %s',(code)=>{expect(getCardAbilityDefinitionsForCardCode(code).find(a=>a.abilityId===ABILITY)).toMatchObject({baseCardCodes:['PL!N-bp3-028'],implemented:true});});
 it('privately inspects one per own Nijigasaki stage member including WAITING',()=>{const s=setup(2);const g=start(s.game);expect(g.activeEffect).toMatchObject({abilityId:ABILITY,inspectionCardIds:['top','rest'],selectableCardVisibility:'AWAITING_PLAYER_ONLY',selectableCardMode:'ORDERED_MULTI',minSelectableCards:1,maxSelectableCards:1,selectionLabel:'选择要放置于卡组顶的卡',confirmSelectionLabel:'放置于卡组顶',canSkipSelection:true,skipSelectionLabel:'全部放置入休息室'});expect(g.inspectionZone.revealedCardIds).toEqual([]);});
 it('excludes non-Nijigasaki, memberBelow, opponent members, and empty slots',()=>{const s=setup(1);const nonNiji=member('non-niji','Liella!');const below=member('below');const opponent=member('opponent','虹ヶ咲',P2);let game=registerCards(s.game,[nonNiji,below,opponent]);game=updatePlayer(game,P1,p=>({...p,memberSlots:{...placeCardInSlot(p.memberSlots,SlotPosition.LEFT,nonNiji.instanceId,{orientation:OrientationState.ACTIVE,face:FaceState.FACE_UP}),memberBelow:new Map([[s.source.instanceId,[below.instanceId]]])}}));game=updatePlayer(game,P2,p=>({...p,memberSlots:placeCardInSlot(p.memberSlots,SlotPosition.CENTER,opponent.instanceId,{orientation:OrientationState.ACTIVE,face:FaceState.FACE_UP})}));const started=start(game);expect(started.activeEffect?.inspectionCardIds).toEqual(['top']);expect(started.activeEffect?.metadata?.nijigasakiMemberCount).toBe(1);});
 it('accepts the real frontend ORDERED_MULTI selectedCardIds submission',()=>{const s=setup(2);const started=start(s.game);const session=createGameSession();session.createGame('connect-ui',P1,'P1',P2,'P2');(session as unknown as {authorityState:typeof started}).authorityState=started;const result=session.executeCommand(createConfirmEffectStepCommand(P1,started.activeEffect!.id,undefined,undefined,undefined,undefined,['top']));expect(result.success).toBe(true);expect(session.state?.activeEffect).toMatchObject({stepId:'PL_N_BP3_028_CONFIRM_REVEALED_TOP',revealedCardIds:['top']});});
 it('returns one selected card to top, groups remainder into waiting, then publicly reveals current top',()=>{const s=setup(2);const reveal=confirm(start(s.game),['top']);expect(reveal.activeEffect).toMatchObject({stepId:'PL_N_BP3_028_CONFIRM_REVEALED_TOP',revealedCardIds:['top'],selectableCardVisibility:'PUBLIC'});const events=reveal.eventLog.map(x=>x.event).filter(e=>e.eventType===TriggerCondition.ON_ENTER_WAITING_ROOM&&e.fromZone===ZoneType.MAIN_DECK);expect(events).toHaveLength(1);expect(events[0]?.cardInstanceIds).toEqual(['rest']);expect(reveal.players[0].mainDeck.cardIds).toEqual(['rest']);});
 it('does not include refresh washback cards outside the inspected remainder in movedCardIds',()=>{const s=setup(2);const waits=[member('wait-1'),member('wait-2'),member('wait-3')];let game=registerCards(s.game,waits);game=updatePlayer(game,P1,p=>({...p,mainDeck:{...p.mainDeck,cardIds:['top']},waitingRoom:{...p.waitingRoom,cardIds:waits.map(c=>c.instanceId)}}));const started=start(game);const inspected=started.activeEffect!.inspectionCardIds!;const reveal=confirm(started,[inspected[0]!]);const event=reveal.eventLog.map(x=>x.event).find(e=>e.eventType===TriggerCondition.ON_ENTER_WAITING_ROOM&&e.fromZone===ZoneType.MAIN_DECK);expect(event?.cardInstanceIds).toEqual([inspected[1]]);for(const card of waits.filter(c=>!inspected.includes(c.instanceId))) expect(event?.cardInstanceIds).not.toContain(card.instanceId);});
 it('skip submits no selectedCardIds and places every inspected card into one waiting event',()=>{const s=setup(2);const started=start(s.game);const session=createGameSession();session.createGame('connect-skip',P1,'P1',P2,'P2');(session as unknown as {authorityState:typeof started}).authorityState=started;const result=session.executeCommand(createConfirmEffectStepCommand(P1,started.activeEffect!.id));expect(result.success).toBe(true);const events=session.state!.eventLog.map(x=>x.event).filter(e=>e.eventType===TriggerCondition.ON_ENTER_WAITING_ROOM&&e.fromZone===ZoneType.MAIN_DECK);expect(events).toHaveLength(1);expect(events[0]?.cardInstanceIds).toEqual(['top','rest']);expect(session.state?.activeEffect?.stepId).toBe('PL_N_BP3_028_CONFIRM_REVEALED_TOP');});
 it('confirms a revealed LIVE back on top and adds source-LIVE SCORE once',()=>{const s=setup(1,true);const reveal=confirm(start(s.game),['top']);const done=confirm(reveal);expect(done.players[0].mainDeck.cardIds[0]).toBe('top');expect(done.inspectionZone.cardIds).toEqual([]);expect(done.liveResolution.liveModifiers).toContainEqual(expect.objectContaining({kind:'SCORE',liveCardId:s.source.instanceId,sourceCardId:s.source.instanceId,abilityId:ABILITY,countDelta:1}));expect(done.liveResolution.playerScores.get(P1)).toBe(1);});
 it('N=0 skips arrange and still reveals; non-LIVE adds no score',()=>{const s=setup(0,false);const reveal=start(s.game);expect(reveal.activeEffect?.stepId).toBe('PL_N_BP3_028_CONFIRM_REVEALED_TOP');const done=confirm(reveal);expect(done.liveResolution.liveModifiers).toEqual([]);expect(done.players[0].mainDeck.cardIds[0]).toBe('top');});
 it('stale inspected cards are safely returned and the forced window is consumed',()=>{const s=setup(2);const started=start(s.game);const stale={...started,inspectionZone:{...started.inspectionZone,cardIds:['top']}};const done=confirm(stale,['top']);expect(done.activeEffect).toBeNull();expect(done.inspectionZone.cardIds).toEqual([]);expect(done.inspectionZone.revealedCardIds).toEqual([]);expect(done.inspectionContext).toBeNull();expect(done.players[0].mainDeck.cardIds[0]).toBe('top');expect(done.liveResolution.liveModifiers).toEqual([]);});
 it('stale revealed card is cleaned up and does not leave a forced window',()=>{const s=setup(0,true);const reveal=start(s.game);const stale={...reveal,inspectionZone:{...reveal.inspectionZone,cardIds:[],revealedCardIds:[]}};const done=confirm(stale);expect(done.activeEffect).toBeNull();expect(done.inspectionContext).toBeNull();expect(done.liveResolution.liveModifiers).toEqual([]);});
 it('source loss during either phase returns current inspection cards and adds no score',()=>{const first=start(setup(2).game);const firstLost=updatePlayer(first,P1,p=>({...p,liveZone:{...p.liveZone,cardIds:[]}}));const firstDone=confirm(firstLost,['top']);expect(firstDone.activeEffect).toBeNull();expect(firstDone.inspectionZone.cardIds).toEqual([]);expect(firstDone.liveResolution.liveModifiers).toEqual([]);const reveal=start(setup(0,true).game);const revealLost=updatePlayer(reveal,P1,p=>({...p,liveZone:{...p.liveZone,cardIds:[]}}));const revealDone=confirm(revealLost);expect(revealDone.activeEffect).toBeNull();expect(revealDone.players[0].mainDeck.cardIds[0]).toBe('top');expect(revealDone.liveResolution.liveModifiers).toEqual([]);});
 it('repeated confirmation cannot duplicate the waiting event or SCORE',()=>{const s=setup(2,true);const reveal=confirm(start(s.game),['top']);const done=confirm(reveal);const repeated=confirmActiveEffectStep(done,P1,'pending');expect(repeated).toBe(done);expect(done.eventLog.filter(x=>x.event.eventType===TriggerCondition.ON_ENTER_WAITING_ROOM)).toHaveLength(1);expect(done.liveResolution.liveModifiers.filter(m=>m.abilityId===ABILITY)).toHaveLength(1);});
 it('keeps a real enter-waiting proving pending behind reveal and starts its interaction after final confirmation',()=>{const s=setup(2,true);const proving=member('PL!SP-bp5-005-R','Liella!',P1);const extra=member('extra');let game=registerCards({...s.game,currentPhase:GamePhase.MAIN_PHASE},[proving,extra]);game=updatePlayer(game,P1,p=>({...p,mainDeck:{...p.mainDeck,cardIds:[...p.mainDeck.cardIds,extra.instanceId]},memberSlots:placeCardInSlot(p.memberSlots,SlotPosition.RIGHT,proving.instanceId,{orientation:OrientationState.ACTIVE,face:FaceState.FACE_UP})}));const reveal=confirm(start(game),['top']);expect(reveal.activeEffect).toMatchObject({abilityId:ABILITY,stepId:'PL_N_BP3_028_CONFIRM_REVEALED_TOP'});expect(reveal.pendingAbilities.some(a=>a.abilityId===PROVING)).toBe(true);const continued=confirm(reveal);expect(continued.activeEffect).toMatchObject({abilityId:PROVING,sourceCardId:proving.instanceId});});
});
