import { describe, expect, it } from 'vitest';
import { createCardInstance, createHeartIcon, createHeartRequirement, type MemberCardData } from '../../src/domain/entities/card';
import { createGameState, registerCards, updatePlayer, type PendingAbilityState } from '../../src/domain/entities/game';
import { placeCardInSlot, removeCardFromSlot } from '../../src/domain/entities/zone';
import { confirmActiveEffectStep, resolvePendingCardEffects } from '../../src/application/card-effect-runner';
import { PL_N_BP3_009_LIVE_START_BOTTOM_TWO_WAITING_MEMBERS_COST_SUM_REWARD_ABILITY_ID as ABILITY, PL_N_BP3_010_LIVE_START_SELECT_PLAYER_BOTTOM_WAITING_MEMBERS_ABILITY_ID as PROVING } from '../../src/application/card-effects/ability-ids';
import { getCardAbilityDefinitionsForCardCode } from '../../src/application/card-effects/definitions/lookup';
import { addLiveModifier } from '../../src/domain/rules/live-modifiers';
import { CardType, FaceState, HeartColor, OrientationState, SlotPosition, TriggerCondition } from '../../src/shared/types/enums';

const P1='p1', P2='p2';
function member(code:string,id:string,cost:number,owner=P1): ReturnType<typeof createCardInstance<MemberCardData>> { return createCardInstance({cardCode:code,name:id,cardType:CardType.MEMBER,cost,blade:1,hearts:[createHeartIcon(HeartColor.PINK,1)]},owner,id); }
function setup(costs=[3,3]) { const source=member('PL!N-bp3-009-R＋','rina',10); const a=member('a','a',costs[0]); const b=member('b','b',costs[1]); const other=member('c','c',4); const live=createCardInstance({cardCode:'live',name:'live',cardType:CardType.LIVE,score:1,requirements:createHeartRequirement({[HeartColor.PINK]:1})},P1,'live'); let game=createGameState('rina',P1,'P1',P2,'P2'); game=registerCards(game,[source,a,b,other,live]); game=updatePlayer(game,P1,p=>({...p,memberSlots:placeCardInSlot(p.memberSlots,SlotPosition.CENTER,source.instanceId,{orientation:OrientationState.ACTIVE,face:FaceState.FACE_UP}),waitingRoom:{...p.waitingRoom,cardIds:[a.instanceId,b.instanceId,live.instanceId]},mainDeck:{...p.mainDeck,cardIds:[other.instanceId]}})); const pending:PendingAbilityState={id:'pending',abilityId:ABILITY,sourceCardId:source.instanceId,controllerId:P1,mandatory:true,timingId:TriggerCondition.ON_LIVE_START,eventIds:[]}; return {game:{...game,pendingAbilities:[pending]},source,a,b,live}; }
function start(game:ReturnType<typeof setup>['game']) { return resolvePendingCardEffects(game).gameState; }
function choose(game:ReturnType<typeof setup>['game'],ids:string[]) { return confirmActiveEffectStep(game,P1,game.activeEffect!.id,undefined,undefined,undefined,undefined,ids); }

describe('PL!N-bp3-009 天王寺璃奈',()=>{
 it.each(['PL!N-bp3-009-R＋','PL!N-bp3-009-P','PL!N-bp3-009-P＋','PL!N-bp3-009-SEC'])('shares the implemented base definition for %s',(code)=>{expect(getCardAbilityDefinitionsForCardCode(code).find(a=>a.abilityId===ABILITY)).toMatchObject({baseCardCodes:['PL!N-bp3-009'],implemented:true});});
 it('opens an exact-two ordered optional selection containing only own waiting-room members',()=>{const s=setup();const g=start(s.game);expect(g.activeEffect).toMatchObject({abilityId:ABILITY,selectableCardIds:['a','b'],selectableCardMode:'ORDERED_MULTI',minSelectableCards:2,maxSelectableCards:2,canSkipSelection:true,skipSelectionLabel:'不发动'});});
 it('moves in submitted order and cost 6 only draws one',()=>{const s=setup([3,3]);const g=choose(start(s.game),['b','a']);expect(g.players[0].mainDeck.cardIds).toEqual(['b','a']);expect(g.players[0].hand.cardIds).toEqual(['c']);expect(g.liveResolution.liveModifiers).toEqual([]);});
 it('cost 8 writes only SOURCE_MEMBER rainbow Heart',()=>{const s=setup([3,5]);const g=choose(start(s.game),['a','b']);expect(g.liveResolution.liveModifiers).toContainEqual(expect.objectContaining({kind:'HEART',target:'SOURCE_MEMBER',sourceCardId:'rina',abilityId:ABILITY,hearts:[{color:HeartColor.RAINBOW,count:1}]}));});
 it('cost 25 writes player total SCORE without liveCardId and refreshes playerScores',()=>{const s=setup([12,13]);const g=choose(start(s.game),['a','b']);const m=g.liveResolution.liveModifiers.find(x=>x.kind==='SCORE');expect(m).toMatchObject({kind:'SCORE',sourceCardId:'rina',abilityId:ABILITY,countDelta:1});expect(m).not.toHaveProperty('liveCardId');expect(g.liveResolution.playerScores.get(P1)).toBe(1);});
 it('declines without moving or rewarding',()=>{const s=setup();const g=choose(start(s.game),[]);expect(g.players[0].waitingRoom.cardIds).toEqual(['a','b','live']);expect(g.liveResolution.liveModifiers).toEqual([]);expect(g.pendingAbilities).toEqual([]);});
 it('rejects non-member, opponent, duplicate, and one-card submissions',()=>{const s=setup();const opponent=member('opp','opp',2,P2);let game=registerCards(s.game,[opponent]);game=updatePlayer(game,P2,p=>({...p,waitingRoom:{...p.waitingRoom,cardIds:['opp']}}));const started=start(game);for(const ids of [['live','a'],['opp','a'],['a','a'],['a']]) expect(choose(started,ids)).toBe(started);});
 it('safely consumes when fewer than two own waiting-room members exist',()=>{const s=setup();const game=updatePlayer(s.game,P1,p=>({...p,waitingRoom:{...p.waitingRoom,cardIds:['a','live']}}));const done=start(game);expect(done.activeEffect).toBeNull();expect(done.pendingAbilities).toEqual([]);expect(done.players[0].waitingRoom.cardIds).toEqual(['a','live']);});
 it('moves other printed cost totals without rewards',()=>{const s=setup([4,5]);const done=choose(start(s.game),['a','b']);expect(done.players[0].mainDeck.cardIds).toEqual(['c','a','b']);expect(done.players[0].hand.cardIds).toEqual([]);expect(done.liveResolution.liveModifiers).toEqual([]);});
 it('ignores MEMBER_COST modifiers on waiting-room printed costs',()=>{const s=setup([3,3]);const modified=addLiveModifier(s.game,{kind:'MEMBER_COST',playerId:P1,memberCardId:'a',countDelta:19,sourceCardId:'rina',abilityId:'test-cost'});const done=choose(start(modified),['a','b']);expect(done.players[0].hand.cardIds).toEqual(['c']);expect(done.liveResolution.liveModifiers.filter(m=>m.abilityId===ABILITY)).toEqual([]);});
 it('refreshes stale candidates when two legal members remain',()=>{const s=setup();const d=member('d','d',2);let started=registerCards(start(s.game),[d]);started=updatePlayer(started,P1,p=>({...p,waitingRoom:{...p.waitingRoom,cardIds:['b','d','live']}}));const refreshed=choose(started,['a','b']);expect(refreshed.activeEffect).toMatchObject({selectableCardIds:['b','d']});expect(refreshed.players[0].mainDeck.cardIds).toEqual(['c']);});
 it('ends safely when stale candidates leave fewer than two members',()=>{const s=setup();let started=start(s.game);started=updatePlayer(started,P1,p=>({...p,waitingRoom:{...p.waitingRoom,cardIds:['b','live']}}));const done=choose(started,['a','b']);expect(done.activeEffect).toBeNull();expect(done.players[0].mainDeck.cardIds).toEqual(['c']);expect(done.liveResolution.liveModifiers).toEqual([]);});
 it('does not pay after the source leaves stage',()=>{const s=setup();let started=start(s.game);started=updatePlayer(started,P1,p=>({...p,memberSlots:removeCardFromSlot(p.memberSlots,SlotPosition.CENTER)}));const done=choose(started,['a','b']);expect(done.activeEffect).toBeNull();expect(done.players[0].waitingRoom.cardIds).toEqual(['a','b','live']);expect(done.liveResolution.liveModifiers).toEqual([]);});
 it('repeated confirmation cannot repeat movement or rewards',()=>{const s=setup([3,5]);const started=start(s.game);const done=choose(started,['a','b']);const repeated=confirmActiveEffectStep(done,P1,'pending',undefined,undefined,undefined,undefined,['a','b']);expect(repeated).toBe(done);expect(done.liveResolution.liveModifiers.filter(m=>m.abilityId===ABILITY)).toHaveLength(1);expect(done.players[0].mainDeck.cardIds).toEqual(['c','a','b']);});
 it('continues into a real following pending interaction',()=>{const s=setup();const proving:PendingAbilityState={id:'proving',abilityId:PROVING,sourceCardId:'rina',controllerId:P1,mandatory:true,timingId:TriggerCondition.ON_LIVE_START,eventIds:[]};const started=start(s.game);const done=choose({...started,pendingAbilities:[proving]},['a','b']);expect(done.activeEffect).toMatchObject({abilityId:PROVING,selectableOptions:[{id:P1,label:'自己'},{id:P2,label:'对方'}]});});
});
