import { describe, expect, it } from 'vitest';
import { createCardInstance, createHeartIcon } from '../../src/domain/entities/card';
import { createGameState, registerCards, updatePlayer, type PendingAbilityState } from '../../src/domain/entities/game';
import { addCardToZone, placeCardInSlot, removeCardFromZone } from '../../src/domain/entities/zone';
import { confirmActiveEffectStep, resolvePendingCardEffects } from '../../src/application/card-effect-runner';
import { addHeartLiveModifierForMember, addMemberCostLiveModifierForMember, isLiveAbilitySuppressed, suppressLiveAbility } from '../../src/domain/rules/live-modifiers';
import { SP_PB1_011_ON_ENTER_REPLAY_OTHER_LIELLA_MEMBER_ABILITY_ID } from '../../src/application/card-effects/ability-ids';
import { CardType, FaceState, HeartColor, OrientationState, SlotPosition, TriggerCondition } from '../../src/shared/types/enums';
const P1='p1',P2='p2';
function member(code:string,name:string,id:string,group='Liella!'){return createCardInstance({cardCode:code,name,groupNames:[group],cardType:CardType.MEMBER,cost:5,blade:1,hearts:[createHeartIcon(HeartColor.PINK,1)]},P1,id)}
function setup(){const source=member('PL!SP-pb1-011-R','鬼塚冬毬','tomari');const target=member('T','澁谷かのん','target');const same=member('T2','澁谷かのん','same');const excluded=member('X','鬼塚冬毬 & マルガレーテ','excluded');let game=registerCards(createGameState('011',P1,'P1',P2,'P2'),[source,target,same,excluded]);game=updatePlayer(game,P1,p=>({...p,memberSlots:placeCardInSlot(placeCardInSlot(placeCardInSlot(p.memberSlots,SlotPosition.LEFT,target.instanceId,{orientation:OrientationState.WAITING,face:FaceState.FACE_UP}),SlotPosition.CENTER,source.instanceId,{orientation:OrientationState.ACTIVE,face:FaceState.FACE_UP}),SlotPosition.RIGHT,excluded.instanceId,{orientation:OrientationState.ACTIVE,face:FaceState.FACE_UP}),waitingRoom:addCardToZone(p.waitingRoom,same.instanceId)}));const pending:PendingAbilityState={id:'pending-011',abilityId:SP_PB1_011_ON_ENTER_REPLAY_OTHER_LIELLA_MEMBER_ABILITY_ID,sourceCardId:source.instanceId,controllerId:P1,mandatory:true,timingId:TriggerCondition.ON_ENTER_STAGE,eventIds:['enter']};return {game:{...game,pendingAbilities:[pending]},source,target,same,excluded};}
describe('PL!SP-pb1-011 Tomari',()=>{
  it('offers only another Liella member, pays it, and replays the exact cardId ACTIVE to its original slot',()=>{const s=setup();const started=resolvePendingCardEffects(s.game).gameState;expect(started.activeEffect?.selectableCardIds).toEqual(['target']);expect(started.activeEffect?.skipSelectionLabel).toBe('不发动');const done=confirmActiveEffectStep(started,P1,'pending-011','target');expect(done.players[0].memberSlots.slots[SlotPosition.LEFT]).toBe('target');expect(done.players[0].memberSlots.cardStates.get('target')?.orientation).toBe(OrientationState.ACTIVE);expect(done.players[0].movedToStageThisTurn).toContain('target');expect(done.players[0].waitingRoom.cardIds).toContain('same');expect(done.eventLog.some(x=>x.event.eventType===TriggerCondition.ON_LEAVE_STAGE)).toBe(true);expect(done.eventLog.some(x=>x.event.eventType===TriggerCondition.ON_ENTER_WAITING_ROOM)).toBe(true);expect(done.eventLog.some(x=>x.event.eventType===TriggerCondition.ON_ENTER_STAGE && 'cardInstanceId' in x.event && x.event.cardInstanceId==='target')).toBe(true);});
  it('declines with no stage or event changes',()=>{const s=setup();const started=resolvePendingCardEffects(s.game).gameState;const before=started.eventLog.length;const done=confirmActiveEffectStep(started,P1,'pending-011',null);expect(done.players[0].memberSlots.slots[SlotPosition.LEFT]).toBe('target');expect(done.eventLog).toHaveLength(before);});
  it('does not require the source to remain on stage',()=>{const s=setup();let started=resolvePendingCardEffects(s.game).gameState;started=updatePlayer(started,P1,p=>({...p,memberSlots:{...p.memberSlots,slots:{...p.memberSlots.slots,[SlotPosition.CENTER]:null}},waitingRoom:addCardToZone(p.waitingRoom,'tomari')}));const done=confirmActiveEffectStep(started,P1,'pending-011','target');expect(done.players[0].memberSlots.slots[SlotPosition.LEFT]).toBe('target');});
  it('replays only the exact paid target when the other same-name waiting-room card is absent',()=>{const s=setup();let started=resolvePendingCardEffects(s.game).gameState;started=updatePlayer(started,P1,p=>({...p,waitingRoom:removeCardFromZone(p.waitingRoom,'same')}));const done=confirmActiveEffectStep(started,P1,'pending-011','target');expect(done.players[0].memberSlots.slots[SlotPosition.LEFT]).toBe('target');expect(done.players[0].waitingRoom.cardIds).not.toContain('same');expect(done.actionHistory.some(action=>action.payload.playedCardId==='same')).toBe(false);});
  it('clears old-instance Heart, cost and WAITING lifecycle state before replay',()=>{const s=setup();let game=addHeartLiveModifierForMember(s.game,{playerId:P1,memberCardId:'target',sourceCardId:'tomari',abilityId:'old-heart',hearts:[createHeartIcon(HeartColor.PURPLE,1)]})!.gameState;game=addMemberCostLiveModifierForMember(game,{playerId:P1,memberCardId:'target',sourceCardId:'tomari',abilityId:'old-cost',countDelta:-2})!.gameState;const started=resolvePendingCardEffects(game).gameState;const done=confirmActiveEffectStep(started,P1,'pending-011','target');expect(done.liveResolution.liveModifiers.some(m=>'memberCardId' in m&&m.memberCardId==='target'||m.kind==='HEART'&&m.target==='TARGET_MEMBER'&&m.targetMemberCardId==='target')).toBe(false);expect(done.players[0].memberSlots.cardStates.get('target')?.orientation).toBe(OrientationState.ACTIVE);});
  it('clears old-instance SUPPRESS_ABILITY while preserving unrelated player and LIVE modifiers',()=>{const s=setup();const playerScore={kind:'SCORE' as const,playerId:P1,countDelta:1,sourceCardId:'other-source',abilityId:'player-score'};const liveRequirement={kind:'REQUIREMENT' as const,liveCardId:'live-card',modifiers:[],sourceCardId:'live-source',abilityId:'live-requirement'};let game={...s.game,liveResolution:{...s.game.liveResolution,liveModifiers:[...s.game.liveResolution.liveModifiers,playerScore,liveRequirement]}};game=suppressLiveAbility(game,{sourceCardId:'target',suppressedAbilityId:'target-ability',abilityId:'suppressor'});expect(isLiveAbilitySuppressed(game,'target','target-ability')).toBe(true);const started=resolvePendingCardEffects(game).gameState;const done=confirmActiveEffectStep(started,P1,'pending-011','target');expect(isLiveAbilitySuppressed(done,'target','target-ability')).toBe(false);expect(done.liveResolution.liveModifiers).toContainEqual(playerScore);expect(done.liveResolution.liveModifiers).toContainEqual(liveRequirement);});
});
