export const REPLAY_RECORD_SCHEMA_VERSION = 1;
export const DEBUG_REPLAY_BUNDLE_SCHEMA_VERSION = 1;
export const LEGACY_GAME_STATE_SCHEMA_VERSION = 'GAME_STATE_V1';
export const GAME_STATE_SCHEMA_VERSION = 'GAME_STATE_V2';
export const SUPPORTED_GAME_STATE_SCHEMA_VERSIONS = [
  LEGACY_GAME_STATE_SCHEMA_VERSION,
  GAME_STATE_SCHEMA_VERSION,
] as const;
export const REPLAY_RULES_VERSION = 'LOVECABATTLE_RULES_V1';
export const REPLAY_CARD_DATA_VERSION = 'ONLINE_RUNTIME_CARD_DATA_SNAPSHOT';
