export const REPLAY_RECORD_SCHEMA_VERSION = 1;
export const DEBUG_REPLAY_BUNDLE_SCHEMA_VERSION = 1;
export const GAME_STATE_SCHEMA_VERSION = 'GAME_STATE_V1';
export const REPLAY_RULES_VERSION = 'LOVECABATTLE_RULES_V1';
export const REPLAY_CARD_DATA_VERSION = 'ONLINE_RUNTIME_CARD_DATA_SNAPSHOT';
